---
title: "Covid19_Regelungen_Datensätze"
author: "Johannes Pfeifer (12129959)"
date: "25 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Quellen siehe R-File
Datensätze aktuell nur bis KW 47 in 2021
(Wenn sich Regelungen unter der Woche ändern, wird die Kalenderwoche bei den neuen Regeln als 1 und bei den alten Regeln als 0 kodiert)

Lockdowns in jedem Bundesland von gleicher Dauer

```{r Regelungen Bayern}
library(tidyverse)

# 2020 Datensatz:

covid_regelungen2020_Bayern <- data.frame(matrix(ncol = 8, nrow = 53))

colnames(covid_regelungen2020_Bayern) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                           "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2020_Bayern <- covid_regelungen2020_Bayern %>% 
  mutate(Jahr = 2020, Bundesland = "Bayern", Drei_G = 0, Zwei_G = 0)

x <- 1  
while (x <= nrow(covid_regelungen2020_Bayern)) {
    covid_regelungen2020_Bayern$KW[x] <- x
    x <- x + 1
  }
  
covid_regelungen2020_Bayern$Lockdown[12:24] <- 1
covid_regelungen2020_Bayern$Lockdown[45:53] <- 1
covid_regelungen2020_Bayern$Lockdown[is.na(covid_regelungen2020_Bayern$Lockdown)] <- 0

covid_regelungen2020_Bayern$Medizinische_Maskenpflicht[18:53] <- 1
covid_regelungen2020_Bayern$Medizinische_Maskenpflicht[is.na(covid_regelungen2020_Bayern$Medizinische_Maskenpflicht)] <- 0
covid_regelungen2020_Bayern$FFP2_Maskenpflicht[1:53] <- 0

# 2021 Datensatz:

covid_regelungen2021_Bayern <- data.frame(matrix(ncol = 8, nrow = 47))

colnames(covid_regelungen2021_Bayern) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                           "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2021_Bayern <- covid_regelungen2021_Bayern %>% 
  mutate(Jahr = 2021, Bundesland = "Bayern")

x <- 1  
while (x <= nrow(covid_regelungen2021_Bayern)) {
  covid_regelungen2021_Bayern$KW[x] <- x
  x <- x + 1
}

covid_regelungen2021_Bayern$Lockdown[1:20] <- 1
covid_regelungen2021_Bayern$Lockdown[is.na(covid_regelungen2021_Bayern$Lockdown)] <- 0

covid_regelungen2021_Bayern$Drei_G[21:46] <- 1
covid_regelungen2021_Bayern$Drei_G[is.na(covid_regelungen2021_Bayern$Drei_G)] <- 0

covid_regelungen2021_Bayern$Zwei_G[47] <- 1
covid_regelungen2021_Bayern$Zwei_G[is.na(covid_regelungen2021_Bayern$Zwei_G)] <- 0

covid_regelungen2021_Bayern$Medizinische_Maskenpflicht[36:44] <- 1
covid_regelungen2021_Bayern$Medizinische_Maskenpflicht[is.na(covid_regelungen2021_Bayern$Medizinische_Maskenpflicht)] <- 0

covid_regelungen2021_Bayern$FFP2_Maskenpflicht[1:35] <- 1
covid_regelungen2021_Bayern$FFP2_Maskenpflicht[45:47] <- 1
covid_regelungen2021_Bayern$FFP2_Maskenpflicht[is.na(covid_regelungen2021_Bayern$FFP2_Maskenpflicht)] <- 0

# Finaler Datensatz:

covid_regelungen_Bayern <- rbind(covid_regelungen2020_Bayern, covid_regelungen2021_Bayern)

```

```{r Regelungen Baden-Württemberg}

# 2020 Datensatz:

covid_regelungen2020_Baden_Wuerttemberg <- data.frame(matrix(ncol = 8, nrow = 53))

colnames(covid_regelungen2020_Baden_Wuerttemberg) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                           "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2020_Baden_Wuerttemberg <- covid_regelungen2020_Baden_Wuerttemberg %>% 
  mutate(Jahr = 2020, Bundesland = "Baden-Württemberg", Drei_G = 0, Zwei_G = 0)

x <- 1  
while (x <= nrow(covid_regelungen2020_Baden_Wuerttemberg)) {
  covid_regelungen2020_Baden_Wuerttemberg$KW[x] <- x
  x <- x + 1
}

covid_regelungen2020_Baden_Wuerttemberg$Lockdown[12:24] <- 1
covid_regelungen2020_Baden_Wuerttemberg$Lockdown[45:53] <- 1
covid_regelungen2020_Baden_Wuerttemberg$Lockdown[is.na(covid_regelungen2020_Baden_Wuerttemberg$Lockdown)] <- 0

covid_regelungen2020_Baden_Wuerttemberg$Medizinische_Maskenpflicht[18:53] <- 1
covid_regelungen2020_Baden_Wuerttemberg$Medizinische_Maskenpflicht[is.na(covid_regelungen2020_Baden_Wuerttemberg$Medizinische_Maskenpflicht)] <- 0
covid_regelungen2020_Baden_Wuerttemberg$FFP2_Maskenpflicht[is.na(covid_regelungen2020_Baden_Wuerttemberg$FFP2_Maskenpflicht)] <- 0

# 2021 Datensatz:

covid_regelungen2021_Baden_Wuerttemberg <- data.frame(matrix(ncol = 8, nrow = 47))

colnames(covid_regelungen2021_Baden_Wuerttemberg) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                                       "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2021_Baden_Wuerttemberg <- covid_regelungen2021_Baden_Wuerttemberg %>% 
  mutate(Jahr = 2021, Bundesland = "Baden-Württemberg")

x <- 1  
while (x <= nrow(covid_regelungen2021_Baden_Wuerttemberg)) {
  covid_regelungen2021_Baden_Wuerttemberg$KW[x] <- x
  x <- x + 1
}

covid_regelungen2021_Baden_Wuerttemberg$Lockdown[1:20] <- 1
covid_regelungen2021_Baden_Wuerttemberg$Lockdown[is.na(covid_regelungen2021_Baden_Wuerttemberg$Lockdown)] <- 0

covid_regelungen2021_Baden_Wuerttemberg$Medizinische_Maskenpflicht[1:47] <- 1

covid_regelungen2021_Baden_Wuerttemberg$FFP2_Maskenpflicht[1:47] <- 0

covid_regelungen2021_Baden_Wuerttemberg$Drei_G[33:46] <- 1
covid_regelungen2021_Baden_Wuerttemberg$Drei_G[is.na(covid_regelungen2021_Baden_Wuerttemberg$Drei_G)] <- 0

covid_regelungen2021_Baden_Wuerttemberg$Zwei_G[47] <- 1
covid_regelungen2021_Baden_Wuerttemberg$Zwei_G[is.na(covid_regelungen2021_Baden_Wuerttemberg$Zwei_G)] <- 0

# Finaler Datensatz:

covid_regelungen_Baden_Wuerttemberg <- rbind(covid_regelungen2020_Baden_Wuerttemberg, covid_regelungen2021_Baden_Wuerttemberg)

```

```{r Regelungen Berlin}

# 2020 Datensatz:

covid_regelungen2020_Berlin <- data.frame(matrix(ncol = 8, nrow = 53))

colnames(covid_regelungen2020_Berlin) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                                       "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2020_Berlin <- covid_regelungen2020_Berlin %>% 
  mutate(Jahr = 2020, Bundesland = "Berlin", Drei_G = 0, Zwei_G = 0)

x <- 1  
while (x <= nrow(covid_regelungen2020_Berlin)) {
  covid_regelungen2020_Berlin$KW[x] <- x
  x <- x + 1
}

covid_regelungen2020_Berlin$Lockdown[12:24] <- 1
covid_regelungen2020_Berlin$Lockdown[45:53] <- 1
covid_regelungen2020_Berlin$Lockdown[is.na(covid_regelungen2020_Berlin$Lockdown)] <- 0

covid_regelungen2020_Berlin$Medizinische_Maskenpflicht[18:53] <- 1
covid_regelungen2020_Berlin$Medizinische_Maskenpflicht[is.na(covid_regelungen2020_Berlin$Medizinische_Maskenpflicht)] <- 0
covid_regelungen2020_Berlin$FFP2_Maskenpflicht[1:53] <- 0

# 2021 Datensatz:

covid_regelungen2021_Berlin <- data.frame(matrix(ncol = 8, nrow = 47))

colnames(covid_regelungen2021_Berlin) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                                       "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2021_Berlin <- covid_regelungen2021_Berlin %>% 
  mutate(Jahr = 2021, Bundesland = "Berlin")

x <- 1  
while (x <= nrow(covid_regelungen2021_Berlin)) {
  covid_regelungen2021_Berlin$KW[x] <- x
  x <- x + 1
}

covid_regelungen2021_Berlin$Lockdown[1:20] <- 1
covid_regelungen2021_Berlin$Lockdown[is.na(covid_regelungen2021_Berlin$Lockdown)] <- 0

covid_regelungen2021_Berlin$Medizinische_Maskenpflicht[24:40] <- 1
covid_regelungen2021_Berlin$Medizinische_Maskenpflicht[is.na(covid_regelungen2021_Berlin$Medizinische_Maskenpflicht)] <- 0

covid_regelungen2021_Berlin$FFP2_Maskenpflicht[13:23] <- 1
covid_regelungen2021_Berlin$FFP2_Maskenpflicht[41:47] <- 1
covid_regelungen2021_Berlin$FFP2_Maskenpflicht[is.na(covid_regelungen2021_Berlin$FFP2_Maskenpflicht)] <- 0

covid_regelungen2021_Berlin$Zwei_G[47] <- 1
covid_regelungen2021_Berlin$Zwei_G[is.na(covid_regelungen2021_Berlin$Zwei_G)] <- 0

# Finaler Datensatz:

covid_regelungen_Berlin <- rbind(covid_regelungen2020_Berlin, covid_regelungen2021_Berlin)

```

```{r Regelungen Brandenburg}

# 2020 Datensatz:

covid_regelungen2020_Brandenburg <- data.frame(matrix(ncol = 8, nrow = 53))

colnames(covid_regelungen2020_Brandenburg) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                           "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2020_Brandenburg <- covid_regelungen2020_Brandenburg %>% 
  mutate(Jahr = 2020, Bundesland = "Brandenburg", Drei_G = 0, Zwei_G = 0)

x <- 1  
while (x <= nrow(covid_regelungen2020_Brandenburg)) {
  covid_regelungen2020_Brandenburg$KW[x] <- x
  x <- x + 1
}

covid_regelungen2020_Brandenburg$Lockdown[12:24] <- 1
covid_regelungen2020_Brandenburg$Lockdown[45:53] <- 1
covid_regelungen2020_Brandenburg$Lockdown[is.na(covid_regelungen2020_Brandenburg$Lockdown)] <- 0

covid_regelungen2020_Brandenburg$Medizinische_Maskenpflicht[18:53] <- 1
covid_regelungen2020_Brandenburg$Medizinische_Maskenpflicht[is.na(covid_regelungen2020_Brandenburg$Medizinische_Maskenpflicht)] <- 0
covid_regelungen2020_Brandenburg$FFP2_Maskenpflicht[1:53] <- 0

# 2021 Datensatz:

covid_regelungen2021_Brandenburg <- data.frame(matrix(ncol = 8, nrow = 47))

colnames(covid_regelungen2021_Brandenburg) <- c("Jahr", "KW", "Bundesland", "Medizinische_Maskenpflicht","FFP2_Maskenpflicht",
                                                "Lockdown", "Drei_G", "Zwei_G")

covid_regelungen2021_Brandenburg <- covid_regelungen2021_Brandenburg %>% 
  mutate(Jahr = 2021, Bundesland = "Brandenburg")

x <- 1  
while (x <= nrow(covid_regelungen2021_Brandenburg)) {
  covid_regelungen2021_Brandenburg$KW[x] <- x
  x <- x + 1
}

covid_regelungen2021_Brandenburg$Lockdown[1:20] <- 1
covid_regelungen2021_Brandenburg$Lockdown[is.na(covid_regelungen2021_Brandenburg$Lockdown)] <- 0

covid_regelungen2021_Brandenburg$Medizinische_Maskenpflicht[1:47] <- 1
covid_regelungen2021_Brandenburg$FFP2_Maskenpflicht[is.na(covid_regelungen2021_Brandenburg$FFP2_Maskenpflicht)] <- 0

covid_regelungen2021_Brandenburg$Zwei_G[47] <- 1
covid_regelungen2021_Brandenburg$Zwei_G[is.na(covid_regelungen2021_Brandenburg$Zwei_G)] <- 0

# Finaler Datensatz:

covid_regelungen_Brandenburg <- rbind(covid_regelungen2020_Brandenburg, covid_regelungen2021_Brandenburg)

```

```{r Regelungen Bremen}


```

```{r Baden-Württwmberg}


```

```{r Baden-Württwmberg}


```

```{r Baden-Württwmberg}


```

```{r Kompletter Covid 19 Regelungen Datensatz}

Covid19_Regelungen <- rbind(covid_regelungen_Bayern, covid_regelungen_Baden_Wuerttemberg, covid_regelungen_Berlin, covid_regelungen_Brandenburg)

```