---
title: "Phu_Auswertung"
author: 'Phu Nguyen (Matrikelnr: 11904670)'
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages <- c("tidyverse", "gghighlight")
lapply(packages, library, character.only = TRUE)
```


```{r Hospitalisierung mit Jahreszeit}
sum_hosp <- fin_datensatz %>%
  select(Jahrwoche, Hospitalisierung, Jahreszeit) %>%
  group_by(Jahrwoche, Jahreszeit) %>%
  summarise(sum(Hospitalisierung)) %>%
  mutate(Jahreszeit = factor(Jahreszeit, levels = c("Fruehling", "Sommer", "Herbst", "Winter")))

ggplot(data = sum_hosp) +
  geom_col(aes(x = Jahrwoche, y = `sum(Hospitalisierung)`, fill = Jahreszeit)) +
  geom_vline(xintercept = "2020-04") +
  geom_vline(xintercept = "2020-18") +
  geom_vline(xintercept = "2020-31") +
  geom_vline(xintercept = "2020-44") +
  geom_vline(xintercept = "2021-04") +
  geom_vline(xintercept = "2021-17") +
  geom_vline(xintercept = "2021-30") +
  geom_vline(xintercept = "2021-43") +
  scale_x_discrete(breaks = sum_hosp$Jahrwoche[c(2, seq(16, 94, 13))]) +
  theme_minimal() +
  scale_fill_manual(values = c("#4daf4a","#ffd92f", "#d95f02", "#377eb8")) +
  ylab("Hospitalisierung")

```


```{r Hospitalisierung nach Altersgruppen}
hosp_alter <- fin_datensatz %>%
  select(Jahrwoche, Altersgruppe, Hospitalisierung) %>%
  group_by(Jahrwoche, Altersgruppe) %>%
  summarise(sum(Hospitalisierung))

ggplot(hosp_alter) +
  geom_line(aes(x = Jahrwoche, y = `sum(Hospitalisierung)`, 
                group = Altersgruppe, color = Altersgruppe), size = 1) +
  scale_x_discrete(breaks = sum_hosp$Jahrwoche[c(seq(1, 98, 20), 98)]) +
  gghighlight() +
  theme_minimal() +
  ylab("Hospitalisierung")
```

```{r Entwicklung Impfquote nach Altersgruppen}
impfquote <- fin_datensatz %>%
  select(Jahrwoche, Impfquote, Altersgruppe, Kalenderwoche) %>%
  group_by(Jahrwoche, Altersgruppe, Kalenderwoche) %>%
  summarise(mean(Impfquote)) %>%
  mutate(Nicht_geimpft = (1 - `mean(Impfquote)`))

impfquote_jung <- impfquote %>%
  filter(Altersgruppe == "00-59") %>%
  mutate(Kalenderwoche = as.integer(Kalenderwoche))
colnames(impfquote_jung)[4] <- "Geimpft"

impfquote_jung %>%
  pivot_longer(!c(Jahrwoche, Altersgruppe, Kalenderwoche), names_to = "Impfstatus", values_to = "Anteil") %>%
  ggplot(aes(x = "", y = Anteil, fill = Impfstatus)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_minimal() +
  theme_void() +
  scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1, labels = c("Geimpft", "Nicht geimpft")) +
  labs(title = "Entwicklung Impfquote bei Jugendlichen") +
  facet_wrap(~ Jahrwoche)

impfquote_alt <- impfquote %>%
  filter(Altersgruppe == "60+") %>%
  mutate(Kalenderwoche = as.integer(Kalenderwoche))
colnames(impfquote_alt)[4] <- "Geimpft"

impfquote_alt %>%
  pivot_longer(!c(Jahrwoche, Altersgruppe, Kalenderwoche), names_to = "Impfstatus", values_to = "Anteil") %>%
  ggplot(aes(x = "", y = Anteil, fill = Impfstatus)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_minimal() +
  theme_void() +
  scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1, labels = c("Geimpft", "Nicht geimpft")) +
  labs(title = "Entwicklung Impfquote bei Alten") +
  facet_wrap(~ Jahrwoche)
```

```{r Streudiagramm Neuerkrankung Hospitalisierung}
log_streu <- ggplot(fin_datensatz) +
  geom_jitter(aes(x = log(Neuerkrankung), y = log(Hospitalisierung), color = Altersgruppe)) +
  scale_color_manual(values = c("#f1a340", "#998ec3")) +
  theme_minimal()

normal_streu <- ggplot(fin_datensatz) +
  geom_point(aes(x = Neuerkrankung, y = Hospitalisierung, color = Altersgruppe)) +
  scale_color_manual(values = c("#f1a340", "#998ec3")) +
  theme_minimal()

ggarrange(normal_streu, log_streu, common.legend = T)
```

