---
title: "auswertung"
author: "Alexander Marquard / 11779957"
date: "11 11 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(smurf)
library(readr)
require("lmtest")
require("prais")
source("funktionen.R")
source("Covid19_Regelungen.R")
```

## Datenerfassung

Hier werden zunächst die Daten erfasst

```{r datenerfassung}

## RKI
# Infektionen
rki_infektionen <- readRDS('../data_truth/RKI/infektionen')

# Impfungen
rki_impfungen <- readRDS('../data_truth/RKI/impfungen')

# Hospitalisierung
rki_hospitalisierung <- readRDS('../data_truth/RKI/hospitalisierung')

# Inzidenz Hospitalisiert
rki_hosp_impf <- readRDS("../daten/inzidenz_hosp.Rds")

rki_inz_sympt <- readRDS("../daten/inzidenz_symptom.Rds")

## LMU
lmu_nowcasting_hosp <- readRDS("../data_truth/LMU/nowcasting_lmu_hosp.Rds")

## KIT
kit_bevoelkerung <- readRDS("../data_truth/KIT/kit_bevoelkerung.Rds")
```

```{r Vergleich bzgl Hospitalisierung}
head(rki_infektionen)
head(rki_impfungen)
head(rki_hospitalisierung)
head(lmu_nowcasting_hosp)

# Vergleiche Hospitalisierung

# lmu:

lmu_nowcasting_hosp <- lmu_nowcasting_hosp %>%
  filter(age60 != "alle") %>%
  mutate(calendarweek = paste(strftime(date, format = '%Y'), 
                                        strftime(date, format = '%V'), 
                                     sep = '-'),
         Altersgruppe = ifelse(age60 != "0-60", "(59, Inf)", "(-Inf, 59]"))

lmu_nowcasting_hosp[which(lmu_nowcasting_hosp$calendarweek == "2021-53"), ]$calendarweek <- "2020-53"

lmu_nowcasting_hosp <- lmu_nowcasting_hosp %>%
  group_by(calendarweek, Altersgruppe) %>%
  summarise(sum_hosp = sum(reported),
            sum_hosp_nowcast = sum(as.numeric(str_replace(nowcast, ",", "."))))

# rki:
rki_hospitalisierung_bayern <- rki_hospitalisierung %>%
  filter(Bundesland_Id == "09") %>%
  mutate(calendarweek = paste(strftime(Datum, format = '%Y'), 
                              strftime(Datum, format = '%V'), 
                              sep = '-'),
         day = weekdays(Datum))

rki_hospitalisierung_bayern[which(rki_hospitalisierung_bayern$calendarweek == "2021-53"), ]$calendarweek <- "2020-53"

rki_hospitalisierung_bayern <- rki_hospitalisierung_bayern %>% filter(day == "Montag") %>%
  select(calendarweek, Altersgruppe, fixierte_7T_Hospitalisierung_Faelle, aktualisierte_7T_Hospitalisierung_Faelle)
  

rki_hospitalisierung_bayern
lmu_nowcasting_hosp

all_together <- left_join(lmu_nowcasting_hosp, rki_hospitalisierung_bayern, by = "calendarweek", suffix = c(".lmu", ".rki"))

all_together <- all_together %>% 
  group_by(calendarweek) %>%
  mutate(sum_hosp = sum(sum_hosp), sum_hosp_nowcast = sum(sum_hosp_nowcast), sum_hosp_week = sum(sum_hosp_week, na.rm = T)) %>%
  mutate(diff_lmu_nowcast_lgl = ifelse(is.na(sum_hosp_week), sum_hosp_nowcast, sum_hosp_nowcast - sum_hosp_week),
         diff_lmu_rki_fix = ifelse(is.na(fixierte_7T_Hospitalisierung_Faelle),sum_hosp, sum_hosp - fixierte_7T_Hospitalisierung_Faelle),
         diff_lmu_rki_akt = ifelse(is.na(aktualisierte_7T_Hospitalisierung_Faelle), sum_hosp, sum_hosp - aktualisierte_7T_Hospitalisierung_Faelle),
         diff_lmu_nowcast_rki_fix = ifelse(is.na(fixierte_7T_Hospitalisierung_Faelle),sum_hosp_nowcast,  sum_hosp_nowcast - fixierte_7T_Hospitalisierung_Faelle),
         diff_lmu_nowcast_rki_akt = ifelse(is.na(aktualisierte_7T_Hospitalisierung_Faelle), sum_hosp_nowcast, sum_hosp_nowcast - aktualisierte_7T_Hospitalisierung_Faelle))

# Teilweise starke Unterschiede zwischen den Zahlen.
# Wir arbeiten im Folgenden mit den Hospitalisierungszahlen der LMU,
# da diese genowcasted sind, wohingegen die Zahlen des RKI zwar für ältere Daten 
# genauer, die aktuellen Zahlen aber unvollständig sind
```

```{r Datensatz Bayern}

rki_infektionen_bayern <- rki_infektionen %>%
  filter(grepl("^9[0-9]{,3}", IdLandkreis)) %>%
  select(-Geschlecht) %>%
  mutate(Altersgruppe = as.factor(Altersgruppe))

levels(rki_infektionen_bayern$Altersgruppe) <- c("(-Inf, 59]", "(-Inf, 59]", 
                                                 "(-Inf, 59]", "(-Inf, 59]", 
                                                 "(59, Inf)","(59, Inf)", 
                                                 "unbekannt")

rki_infektionen_bayern <- rki_infektionen_bayern %>%
  filter(!(Meldedatum == "2021-01-07" & Refdatum == "2020-01-02")) %>%  # filter this observation because it is obviously wrong
  mutate(calendarweek = paste(strftime(Meldedatum, format = '%Y'), 
                              strftime(Meldedatum, format = '%V'), 
                              sep = '-'),
         KW = strftime(Meldedatum, format = '%V'),
         year = strftime(Meldedatum, format = '%Y')) %>%
  arrange(calendarweek)

rki_infektionen_bayern[which(rki_infektionen_bayern$calendarweek == "2021-53"), ]$year <- "2020"
rki_infektionen_bayern[which(rki_infektionen_bayern$calendarweek == "2021-53"), ]$calendarweek <- "2020-53"


rki_infektionen_bayern <- rki_infektionen_bayern %>%
  group_by(calendarweek, Altersgruppe) %>% 
  filter(Altersgruppe != "unbekannt") %>%  # remove all "unbekannt"
  summarise(infektionen = sum(AnzahlFall), KW = unique(KW), year = unique(year))

# combine datasets

faelle_und_hosp_bayern <- inner_join(lmu_nowcasting_hosp, rki_infektionen_bayern, by = c("calendarweek", "Altersgruppe"))

# ergänze Lag

faelle_und_hosp_bayern <- faelle_und_hosp_bayern %>%
  mutate(calendarweek = as.factor(calendarweek),
         KW = as.numeric(KW)) %>%
  group_by(Altersgruppe) %>%
  mutate(lag_1 = lag(infektionen),
         lag_2 = lag(infektionen, 2),
         lag_3 = lag(infektionen, 3))
  

# ergänze seasons

faelle_und_hosp_bayern$season <- add.Seasons(faelle_und_hosp_bayern, "KW", 
                                             useWeeks = T, sep = "-")

# ergänze impfquote
# wir sind nur an der zweitimpfung interessiert und vernachlässigen booster impfungen (vorerst)

rki_impfungen_iq <- rki_impfungen %>%
  filter(Impfschutz == 2) %>% 
  filter(grepl("^09[0-9]{,3}", LandkreisId_Impfort)) %>%
  mutate(Altersgruppe = as.factor(Altersgruppe)) %>%
  mutate(calendarweek = paste(strftime(Impfdatum, format = '%Y'), 
                              strftime(Impfdatum, format = '%V'), 
                              sep = '-'))

levels(rki_impfungen_iq$Altersgruppe) <- c("(-Inf, 59]", "(-Inf, 59]", "(59, Inf)")

rki_impfungen_iq <- rki_impfungen_iq %>%
  group_by(calendarweek, Altersgruppe) %>%
  summarise(anz_geimpft = sum(Anzahl)) %>%
  group_by(Altersgruppe) %>%
  arrange(calendarweek) %>%
  mutate(anz_geimpft_sum = cumsum(anz_geimpft))

kit_bevoelkerung_bayern <- kit_bevoelkerung %>%
  filter(location == "Bayern") %>%
  mutate(age_group = as.factor(age_group))

levels(kit_bevoelkerung_bayern$age_group) <- c("no_vaccine", "total", 
                                               "no_vaccine", "(-Inf, 59]",
                                               "(-Inf, 59]", "(59, Inf)", 
                                               "(59, Inf)")

kit_bevoelkerung_bayern <- kit_bevoelkerung_bayern %>%
  group_by(age_group) %>%
  summarise(pop = sum(population)) %>%
  filter(age_group != "total" & age_group != "no_vaccine") %>%
  mutate(Altersgruppe = age_group) %>%
  select(-age_group)

rki_impfung_iq_w_pop <- inner_join(rki_impfungen_iq, kit_bevoelkerung_bayern, by = "Altersgruppe")
rki_impfung_iq_w_pop <- rki_impfung_iq_w_pop %>%
  group_by(Altersgruppe) %>%
  arrange(calendarweek) %>%
  mutate(anz_geimpft_sum = cumsum(anz_geimpft)) %>%
  mutate(iquote = round((anz_geimpft_sum / pop) * 100, digits = 2))


faelle_und_hosp_bayern_w_iq <- left_join(faelle_und_hosp_bayern, rki_impfung_iq_w_pop, by = c("calendarweek", "Altersgruppe"))

faelle_und_hosp_bayern_w_iq <- faelle_und_hosp_bayern_w_iq %>%
  mutate(anz_geimpft = ifelse(is.na(anz_geimpft), 0, anz_geimpft),
         anz_geimpft_sum = ifelse(is.na(anz_geimpft_sum), 0, anz_geimpft_sum),
         iquote = ifelse(is.na(iquote), 0, iquote)) %>%
  select(-pop)

# ergänze Lockdown

head(covid_regelungen_Bayern)
covid_regelungen_Bayern <- covid_regelungen_Bayern %>%
  mutate(year = as.character(Jahr)) 
faelle_und_hosp_bayern_w_iq_w_Regeln <- left_join(faelle_und_hosp_bayern_w_iq, covid_regelungen_Bayern[, c("KW","year","Lockdown")], by = c("KW", "year"))
faelle_und_hosp_bayern_w_iq_w_Regeln <- faelle_und_hosp_bayern_w_iq_w_Regeln %>%
  mutate(Lockdown = ifelse(is.na(Lockdown), 0, Lockdown)) %>%
  mutate(Lockdown = as.factor(Lockdown))


# ergänze hosp + geimpft
head(rki_hosp_impf)
rki_hosp_impf_a <- rki_hosp_impf %>%
  pivot_longer(cols = -Meldewoche, names_to = "Impfstatus_Altersgruppe") %>%
  mutate(Impfstatus = regmatches(Impfstatus_Altersgruppe, 
                                regexpr("[[:alpha:]]*", Impfstatus_Altersgruppe)),
         Altersgruppe = regmatches(Impfstatus_Altersgruppe, 
                                   regexpr("[0-9]{2}[-+][0-9]{0,2}", 
                                           Impfstatus_Altersgruppe))) %>%
  mutate(Altersgruppe = as.factor(Altersgruppe),
         Impfstatus = as.factor(Impfstatus))
  
levels(rki_hosp_impf_a$Altersgruppe) <- c("(-Inf, 59]", "(-Inf, 59]", "(59, Inf)")
 
rki_hosp_impf_a <- rki_hosp_impf_a %>%
  group_by(Meldewoche, Altersgruppe, Impfstatus) %>%
  summarise(inzidenz = sum(value)) %>%
  group_by(Meldewoche, Altersgruppe) %>%
  mutate(inzidenz_total_hosp = sum(inzidenz)) %>%
  group_by(Meldewoche, Altersgruppe, Impfstatus) %>%
  mutate(quote = round(inzidenz / inzidenz_total_hosp, 2)) %>%
  mutate(KW = Meldewoche,
         year = "2021") %>%
  group_by(Altersgruppe) %>%
  select(-inzidenz) %>%
  spread(Impfstatus, quote)


# ergänze symptomatisch + geimpft
head(rki_inz_sympt)
rki_inz_sympt_a <- rki_inz_sympt %>%
  pivot_longer(cols = -Meldewoche, names_to = "Impfstatus_Altersgruppe") %>%
  mutate(Impfstatus = regmatches(Impfstatus_Altersgruppe, 
                                regexpr("[[:alpha:]]*", Impfstatus_Altersgruppe)),
         Altersgruppe = regmatches(Impfstatus_Altersgruppe, 
                                   regexpr("[0-9]{2}[-+][0-9]{0,2}", 
                                           Impfstatus_Altersgruppe))) %>%
  mutate(Altersgruppe = as.factor(Altersgruppe),
         Impfstatus = as.factor(Impfstatus))
  
levels(rki_inz_sympt_a$Altersgruppe) <- c("(-Inf, 59]", "(-Inf, 59]", "(59, Inf)")
 
rki_inz_sympt_a <- rki_inz_sympt_a %>%
  group_by(Meldewoche, Altersgruppe, Impfstatus) %>%
  summarise(inzidenz = sum(value)) %>%
  group_by(Meldewoche, Altersgruppe) %>%
  mutate(inzidenz_total_sympt = sum(inzidenz)) %>%
  group_by(Meldewoche, Altersgruppe, Impfstatus) %>%
  mutate(quote = round(inzidenz / inzidenz_total_sympt, 2)) %>%
  mutate(KW = Meldewoche,
         year = "2021") %>%
  group_by(Altersgruppe) %>%
  select(-inzidenz) %>%
  spread(Impfstatus, quote)

# join hosp + geimpft
faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote <- 
  left_join(faelle_und_hosp_bayern_w_iq_w_Regeln, 
            rki_hosp_impf_a, 
            by = c("KW", "year", "Altersgruppe"))

faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote <-
  faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote %>%
  select(-Meldewoche) %>%
  mutate(Ungeimpfte_hosp = sum_hosp_nowcast * Ungeimpfte,
         Geimpfte_hosp = sum_hosp_nowcast * Vollständig,
         Ungeimpfte_hosp_quote = Ungeimpfte,
         Vollständig_hosp_quote = Vollständig) %>%
  select(-c(Vollständig, Ungeimpfte))

# join infekt + geimpft

faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote <-
  left_join(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote, 
            rki_inz_sympt_a, 
            by = c("KW", "year", "Altersgruppe"))

faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote <-
  faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote %>%
  select(-Meldewoche) %>%
  mutate(Ungeimpfte_infektionen = infektionen * Ungeimpfte,
         Geimpfte_infektionen = infektionen * Vollständig,
         Ungeimpfte_infektionen_quote = Ungeimpfte,
         Vollständig_infektionen_quote = Vollständig) %>%
  select(-c(Ungeimpfte, Vollständig)) %>%
  # ergänze Lag für impfungen + sympt
  group_by(Altersgruppe) %>%
  mutate(infekt_ungeimpft_lag1 = lag(Ungeimpfte_infektionen),
         infekt_ungeimpft_lag2 = lag(Ungeimpfte_infektionen, 2),
         infekt_geimpft_lag1 = lag(Geimpfte_infektionen),
         infekt_geimpft_lag2 = lag(Geimpfte_infektionen, 2)) %>%
  group_by(Altersgruppe)  %>%
  mutate(anz_geimpft_lag1 = lag(anz_geimpft_sum),
         anz_geimpft_lag2 = lag(anz_geimpft_sum, 2))


corrplot::corrplot(cor(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote[, -c(1,2,6,7,11,15)] %>% na.omit()))
  
faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$KW <- 
  as.factor(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$KW)
faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$year <- 
  as.factor(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$year)
faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$season <- 
  as.factor(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$season)
faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$Altersgruppe <-
  as.factor(faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote$Altersgruppe)

final_df <- faelle_und_hosp_bayern_w_iq_w_Regeln_w_inzquote

# Nicht sonderlich gut, da viele Beobachtungen NA enthalten

model <- lm(log(sum_hosp_nowcast) ~ Altersgruppe +
            log(infekt_geimpft_lag1) +
              log(infekt_geimpft_lag2), 
                   data = final_df)
summary(model)

final_df_wo_na <- final_df %>% na.omit()

model2 <- lm(log(sum_hosp_nowcast) ~ Altersgruppe +
            log(infekt_geimpft_lag1) +
              log(infekt_geimpft_lag2), 
                   data = final_df_wo_na)
summary(model2)

eps_sq <- model2$residuals^2
lm_der_eps <- lm(log(eps_sq) ~ Altersgruppe + log(infekt_geimpft_lag1) + log(infekt_geimpft_lag2), data = final_df_wo_na)
summary(lm_der_eps)
w_i <- 1/exp(fitted.values(lm_der_eps))
model2_w <- lm(formula = log(sum_hosp_nowcast) ~ Altersgruppe + log(infekt_geimpft_lag1) + 
    log(infekt_geimpft_lag2), data = final_df_wo_na, weights = w_i)
summary(model2_w)

hist(log(final_df_wo_na$sum_hosp_nowcast),
     freq = F)
lines(density(log(final_df_wo_na$sum_hosp_nowcast)))

plot(final_df_wo_na$Altersgruppe, log(final_df_wo_na$sum_hosp_nowcast))
plot(log(final_df_wo_na$lag_1), log(final_df_wo_na$sum_hosp_nowcast))
plot(final_df_wo_na$season, log(final_df_wo_na$sum_hosp_nowcast))
plot(final_df_wo_na$season, log(final_df_wo_na$lag_1))

plot(model)
```

```{r Main Model}

# da wir sehr wenige daten bzgl impfung + symptom haben hier modell ohne 

final_df_wo_impfung <- final_df[, -seq(16,24,1)] %>% na.omit()
final_df_wo_impfung <- final_df_wo_impfung[-c(1,2,3,4), ]

## Main Model

final_df_wo_impfung$season <- relevel(final_df_wo_impfung$season, ref = "Summer")

main_model<- lm(log(sum_hosp_nowcast) ~ Altersgruppe +
                  season + log(lag_1) + log(lag_2), 
                   data = final_df_wo_impfung)

# Das hier in Präsentation
summary(main_model)


y_pred_main <- predict(main_model, newdata = final_df_wo_impfung, 
                       interval = "confidence")

y_forecast <- predict(main_model, 
                      newdata = data.frame(calendarweek = c("2021-48","2021-48"),
                                          Altersgruppe = as.factor(c("(-Inf, 59]", 
                                                                     "(59, Inf)")),
                                          KW = as.factor(c("48", "48")),
                                          lag_1 = c(70799, 14172),
                                          lag_2 = c(74379, 15038),
                                          season = as.factor(c("Winter", "Winter"))
                                          ),
                      interval = "confidence")

y_forecast <- data.frame(fit = exp(y_forecast[,1]), 
                         Altersgruppe = as.factor(c("(-Inf, 59]", "(59, Inf)")),
                         calendarweek = c("2021-48", "2021-48"),
                         KW = as.factor(c("48", "48")), 
                         lwr = exp(y_forecast[,2]), 
                         upper = exp(y_forecast[,3]),
                         Lockdown = as.factor(c(0,0)))

ggplot(data.frame(y_true = final_df_wo_impfung$sum_hosp_nowcast, 
                  y_pred = exp(y_pred_main[, 1]), 
                  lwr = exp(y_pred_main[, 2]), upper = exp(y_pred_main[, 3]),
                  cw = final_df_wo_impfung$calendarweek, 
                  Altersgruppe = final_df_wo_impfung$Altersgruppe)) +
  geom_line(aes(x = cw, y = y_pred, group = Altersgruppe, col = "red")) +
  geom_ribbon(aes(x = cw, y = y_pred, ymin = lwr, ymax = upper, 
                  group = Altersgruppe), 
              alpha = 0.2) +
  geom_line(aes(x = cw, y = y_true, group = Altersgruppe, col = "black")) +
  geom_point(data = y_forecast, 
             aes(x = calendarweek, y = fit, group = Altersgruppe, col = "orange"), 
             size = 3) +
  geom_segment(data = y_forecast, 
               aes(x = calendarweek, xend = calendarweek, y = lwr, yend = upper, 
                   group = Altersgruppe, col = "orange"), 
               size = 3, alpha = 0.3) +
  facet_wrap(~Altersgruppe) +
  geom_vline(xintercept = "2021-48", linetype="dotted") +
  scale_colour_manual(name = 'Values', 
         values =c('black'='black',  'red' = 'red', 'orange' = 'orange'), 
         labels = c('True', 'Predicted', 'Forecast')) +
  xlab("Jahrwoche") + ylab("Hospitalisierte Fälle") +
  # labs(title = "Hospitalisierte Fälle nach Altersgruppen") +
  scale_x_discrete(breaks = c("2020-30","2021-10","2021-48")) +
  theme_minimal() +
  theme(text = element_text(size = 25))



# Stepwise regression model
final_df_wo_impfung$sum_hosp_nowcast_log <- log(final_df_wo_impfung$sum_hosp_nowcast + 1)
final_df_wo_impfung$lag_1_log <- log(final_df_wo_impfung$lag_1 + 1)
final_df_wo_impfung$lag_2_log <- log(final_df_wo_impfung$lag_2 + 1)
final_df_wo_impfung$lag_3_log <- log(final_df_wo_impfung$lag_3 + 1)
final_df_wo_impfung$anz_geimpft_sum_log <- log(final_df_wo_impfung$anz_geimpft_sum + 1)
final_df_wo_impfung$anz_geimpft_log <- log(final_df_wo_impfung$anz_geimpft + 1)
final_df_wo_impfung$anz_geimpft_lag1_log <- log(final_df_wo_impfung$anz_geimpft_lag1 + 1) 
final_df_wo_impfung$anz_geimpft_lag2_log <- log(final_df_wo_impfung$anz_geimpft_lag2 + 1) 

full.model <- lm(sum_hosp_nowcast_log ~ . - sum_hosp - sum_hosp_nowcast - calendarweek - Lockdown - KW, 
                   data = final_df_wo_impfung)

step.model <- MASS::stepAIC(full.model, direction = "backward", 
                      trace = FALSE)
summary(step.model)
plot(step.model)

ggplot(data.frame(y_true = final_df_wo_impfung$sum_hosp_nowcast, 
                  y_pred = exp(fitted.values(step.model)), 
                  cw = final_df_wo_impfung$calendarweek, 
                  Altersgruppe = final_df_wo_impfung$Altersgruppe)) +
  geom_line(aes(x = cw, y = y_pred, group = Altersgruppe, col = "red")) +
  geom_line(aes(x = cw, y = y_true, group = Altersgruppe, col = "black")) +
  facet_wrap(~Altersgruppe) +
  scale_colour_manual(name = 'Values', 
         values =c('black'='black',  'red' = 'red'), 
         labels = c('True', 'Predicted')) +
  xlab("Jahrwoche") + ylab("Hospitalisierte Fälle") +
  # labs(title = "Hospitalisierte Fälle nach Altersgruppen") +
  scale_x_discrete(breaks = c("2020-30","2021-10","2021-48")) +
  theme_minimal() +
  theme(text = element_text(size = 25))

# Anhang:
# Überprüfen auf Normalverteilung der Responsevariable

par(mfrow = c(1,2))
hist(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(-Inf, 59]", ]$sum_hosp_nowcast,
     freq = F,
     main = "Histogramm der Hospitalisierungen 0 - 59",
     xlab = "Hospitalisierungen")

hist(log(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(-Inf, 59]", ]$sum_hosp_nowcast),
     freq = F,
     main = "",
     xlab = "log. Hospitalisierungen")
lines(density(log(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(-Inf, 59]", ]$sum_hosp_nowcast)), col = "blue")

par(mfrow = c(1,2))
hist(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(59, Inf)", ]$sum_hosp_nowcast,
     freq = F,
     main = "Histogramm der Hospitalisierungen 59 - Inf",
     xlab = "Hospitalisierungen")

hist(log(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(59, Inf)", ]$sum_hosp_nowcast),
     freq = F,
     main = "",
     xlab = "log. Hospitalisierungen")
lines(density(log(final_df_wo_impfung[final_df_wo_impfung$Altersgruppe == "(59, Inf)", ]$sum_hosp_nowcast)), col = "blue")

# Normalverteilung ist nicht wirklich gegeben. 

# Anhang:
bptest(main_model)
# Teste auf Homoskedastische Störterme: Breusch Pagan
# Test ergibt, dass die Störterme heteroskedastisch sind

# versuche den Fehler durch gewichtung zu beheben
eps_sq <- main_model$residuals^2
lm_der_eps <- lm(log(eps_sq) ~ Altersgruppe +
                  season + log(lag_1) + log(lag_2), 
                   data = final_df_wo_impfung)
summary(lm_der_eps)

w_i <- 1/exp(fitted.values(lm_der_eps))

main_model_w <- lm(log(sum_hosp_nowcast) ~ Altersgruppe +
                  season + log(lag_1) + log(lag_2), 
                   data = final_df_wo_impfung, weights = w_i)

summary(main_model_w)

# Anhang:

par(mfrow = c(2,2))
plot(main_model)
par(mfrow = c(1,1))



# Anhang: 
# durbin watson test auf autokorreliertheit
# Bei autokorrelierten Störgrößen bietet sich ein prais_winsten schätzer an
# Dieser berechnet zunächst ein ungewichtetes LM, berechnet die korrelation
# zwischen den störgrößen rho = sum(eps_i * eps_(i-1)) / sqrt(sum(eps_i^2) * sqrt(sum(eps_(i-1)^2))
# setzt rho in die Gewichtsmatrix W ein, wodurch eine schätzer für
# W erhalten wird W^ und berechnet dann den gewichteten KQ. DIe Schritte werden
# mehrere male wiederholt
 
dwtest(main_model)
# störterme sind autokorreliert

resid <- main_model$residuals

rho <- sum(resid * lag(resid), na.rm = T) / (sqrt(sum(resid^2)) * sqrt(sum(lag(resid^2), na.rm = T)))

main_model_2 <- prais_winsten(formula = log(sum_hosp_nowcast) ~ Altersgruppe +
                  season + log(lag_1) + log(lag_2), 
                   data = final_df_wo_impfung, index = "calendarweek")

summary(main_model_2)

y_pred_main_2 <- main_model_2$fitted.values

ggplot(data.frame(y_true = final_df_wo_impfung$sum_hosp_nowcast, 
                  y_pred = exp(y_pred_main[, 1]), 
                  y_pred2 = exp(y_pred_main_2),
                  lwr = exp(y_pred_main[, 2]), upper = exp(y_pred_main[, 3]),
                  cw = final_df_wo_impfung$calendarweek, 
                  Altersgruppe = final_df_wo_impfung$Altersgruppe)) +
  geom_line(aes(x = cw, y = y_pred, group = Altersgruppe, col = "red")) +
  geom_ribbon(aes(x = cw, y = y_pred, ymin = lwr, ymax = upper, 
                  group = Altersgruppe), 
              alpha = 0.2) +
  geom_line(aes(x = cw, y = y_true, group = Altersgruppe, col = "black")) +
  geom_line(aes(x = cw, y = y_pred2, group = Altersgruppe, col = "green")) +
  geom_point(data = y_forecast, 
             aes(x = calendarweek, y = fit, group = Altersgruppe, col = "orange"), 
             size = 3) +
  geom_segment(data = y_forecast, 
               aes(x = calendarweek, xend = calendarweek, y = lwr, yend = upper, 
                   group = Altersgruppe, col = "orange"), 
               size = 3, alpha = 0.3) +
  facet_wrap(~Altersgruppe) +
  geom_vline(xintercept = "2021-42", linetype="dotted") +
  scale_colour_manual(name = 'Values', 
         values =c('black'='black', 'green' = 'green', 'red' = 'red', 'orange' = 'orange'), 
         labels = c('True', 'Prais_Winsten','Predicted', 'Forecast')) +
  xlab("Kalenderwoche") + ylab("Hospitalisierte Fälle") +
  labs(title = "Hospitalisierte Fälle nach Altersgruppen") +
  scale_x_discrete(breaks = c("2020-30","2021-10","2021-48")) +
  theme_minimal() +
  theme(text = element_text(size = 20))

```



```{r lasso und weiteres}

formula_grouped_lasso <- 
  log(sum_hosp_nowcast) ~ p(Altersgruppe, pen = "grouplasso", group = 1) +
  p(Lockdown, pen = "grouplasso", group = 2) +
  p(season, pen = "grouplasso", group = 3) +
  p(year, pen = "grouplasso", group = 4) +
  p(log(anz_geimpft_lag1 + 1), pen = "lasso") +
  p(log(lag_1), pen ="lasso") +
  p(log(lag_2), pen ="lasso")

group_smurf <-
  glmsmurf(
    formula = formula_grouped_lasso,
    family = gaussian(),
    data = final_df_wo_impfung,
    pen.weights = "glm.stand",
    lambda = "cv.mse"
  )

summary(group_smurf)

y_pred_lasso <- predict_reest(object = group_smurf,
                newdata = final_df_wo_impfung[,-4],
                type = "response")

y_true <- final_df_wo_impfung$sum_hosp_nowcast
  
ggplot(data.frame(y_true = y_true, y_pred_lasso = exp(y_pred_lasso), 
                  x = final_df_wo_impfung$calendarweek, 
                  ag = final_df_wo_impfung$Altersgruppe)) +
  geom_line(aes(y = y_true, x = x, group = ag, col = "black")) +
  geom_line(aes(y = y_pred_lasso, x = x, group = ag, col = "red")) +
  facet_wrap(~ag, scales = "free") +
  scale_x_discrete(breaks = c("2020-20", "2020-50", "2021-20", "2021-47")) +
  xlab("Meldewoche") + ylab("Hospitalisiert") + 
  labs(title = "Prediction vs True Values of Hospitalization", 
       subtitle = "By Age") +
  scale_colour_manual(name = 'Values', 
         values =c('black'='black', 'red' = 'red'), 
         labels = c('True', 'Predicted_lasso')) +
  theme_minimal() +
  theme(text = element_text(size = 30))

# nun als Prediction mit 80% der daten zum modellieren und 20% der daten zum testen

train_df <- final_df_wo_impfung[final_df_wo_impfung$calendarweek <= "2021-41", ]
test_df <- final_df_wo_impfung[final_df_wo_impfung$calendarweek > "2021-41", ]

model_train <- lm(log(sum_hosp_nowcast) ~ Altersgruppe +
                  season + log(anz_geimpft_lag1 + 1) + log(lag_1) + log(lag_2) + 
                    Lockdown, 
                   data = train_df)

summary(model_train)

y_test <- predict(model_train, newdata = test_df, interval = "confidence")

y_forecast <- predict(model_train, 
                      newdata = data.frame(calendarweek = c("2021-48","2021-48"),
                                          Altersgruppe = as.factor(c("(-Inf, 59]", 
                                                                     "(59, Inf)")),
                                          KW = as.factor(c("48", "48")),
                                          lag_1 = c(70799, 14172),
                                          lag_2 = c(74379, 15038),
                                          season = as.factor(c("Winter", "Winter")),
                                          anz_geimpft_lag1 = c(5729870, 3034198),
                                          Lockdown = as.factor(c(0,0))
                                          ),
                      interval = "confidence")

y_forecast <- data.frame(fit = exp(y_forecast[,1]), 
                         Altersgruppe = as.factor(c("(-Inf, 59]", "(59, Inf)")),
                         calendarweek = c("2021-48", "2021-48"),
                         KW = as.factor(c("48", "48")), 
                         lwr = exp(y_forecast[,2]), 
                         upper = exp(y_forecast[,3]),
                         Lockdown = as.factor(c(0,0)))

ggplot(data.frame(y_true = test_df$sum_hosp_nowcast, y_pred = exp(y_test[, 1]), 
                  lwr = exp(y_test[, 2]), upper = exp(y_test[, 3]),
                  cw = test_df$calendarweek, Altersgruppe = test_df$Altersgruppe)) +
  geom_line(aes(x = cw, y = y_pred, group = Altersgruppe, col = "red")) +
  geom_ribbon(aes(x = cw, y = y_pred, ymin = lwr, ymax = upper, 
                  group = Altersgruppe), 
              alpha = 0.2) +
  geom_line(aes(x = cw, y = y_true, group = Altersgruppe, col = "black")) +
  geom_line(data = rbind(train_df,test_df[c(1,2),]), 
            aes(x = calendarweek, 
                y = sum_hosp_nowcast, group = Altersgruppe), col = "black") +
  geom_point(data = y_forecast, 
             aes(x = calendarweek, y = fit, group = Altersgruppe, col = "orange"), 
             size = 3) +
  geom_segment(data = y_forecast, 
               aes(x = calendarweek, xend = calendarweek, y = lwr, yend = upper, 
                   group = Altersgruppe, col = "orange"), 
               size = 3, alpha = 0.3) +
  facet_wrap(~Altersgruppe) +
  geom_vline(xintercept = "2021-42", linetype="dotted") +
  scale_colour_manual(name = 'Values', 
         values =c('black'='black', 'red' = 'red', 'orange' = 'orange'), 
         labels = c('True', 'Predicted', 'Forecast')) +
  xlab("Kalenderwoche") + ylab("Hospitalisierte Fälle") +
  labs(title = "Hospitalisierte Fälle nach Altersgruppen") +
  scale_x_discrete(breaks = c("2021-10","2021-48")) +
  theme_minimal() +
  theme(text = element_text(size = 20))

plot(model_train)

```



