---
title: "ets"
author: "Alexander Marquard / 11779957"
date: "6 3 2022"
output: pdf_document
---

```{r prep}
final_df <- readRDS("../final_df.RDS")
final_comp <- final_df
final_df <- final_df %>% filter(Meldedatum <= "2022-01-30")
impfungen <- readRDS("../../data_truth/RKI/impfungen.Rds")

N <- sum(unique(final_df$population))
unique(final_df$Bundesland)
```

## arima

### Baden-Wuerttemberg

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Baden-Wuerttemberg") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Baden-Wuerttemberg") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
png(filename="./Bilder/fc_bw.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Baden-Wuerttemberg using ARIMA(0,1,1)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,1), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Bayern

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Bayern") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Bayern") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
png(filename="./Bilder/fc_by.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Bayern using ARIMA(1,0,2)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,0,2), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Berlin

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Berlin") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Berlin") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_ber.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Berlin using ARIMA(1,1,3)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,1,3), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```


### Brandenburg

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Brandenburg") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Brandenburg") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_bb.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Brandenburg using ARIMA(0,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```

### Bremen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Bremen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Bremen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_bre.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Bremen using ARIMA(0,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```


### Hamburg

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Hamburg") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Hamburg") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_Ham.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Hamburg using ARIMA(0,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```

### Hessen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Hessen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Hessen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_hes.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Hessen using ARIMA(0,1,1)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,1), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```


### Mecklenburg-Vorpommern

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Mecklenburg-Vorpommern") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Mecklenburg-Vorpommern") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
png(filename="./Bilder/fc_mv.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Mecklenburg-Vorpommern using ARIMA(1,1,2)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,1,2), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```


### Niedersachsen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Niedersachsen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Niedersachsen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_ns.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Niedersachsen using ARIMA(0,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Nordrhein-Westfalen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Nordrhein-Westfalen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Nordrhein-Westfalen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_nrw.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Nordrhein-Westfalen using ARIMA(0,1,1)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,1), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Rheinland-Pfalz

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Rheinland-Pfalz") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Rheinland-Pfalz") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_rp.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Rheinland-Pfalz using ARIMA(0,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(0,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Saarland

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Saarland") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Saarland") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_saar.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Saarland using ARIMA(1,1,1)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,1,1), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Sachsen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Sachsen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Sachsen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_sachs.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Sachsen using ARIMA(5,1,2)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(5,1,2), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Sachsen-Anhalt

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Sachsen-Anhalt") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Sachsen-Anhalt") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_sachs-anh.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Sachsen-Anhalt using ARIMA(1,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```

### Schleswig-Holstein

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Schleswig-Holstein") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Schleswig-Holstein") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_sh.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Schleswig-Holstein using ARIMA(1,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(1,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 1), p_test)
```

### Thueringen

```{r}
p_comp <- final_comp %>% group_by(Meldedatum) %>% filter(Bundesland == "Thueringen") %>% 
  filter(Meldedatum <= "2022-02-13") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) %>% select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))

p_acf <- final_df %>% group_by(Meldedatum) %>% filter(Bundesland == "Thueringen") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung)) 

m_h <- mean(p_acf$Hospitalisierung)
s_h <- sd(p_acf$Hospitalisierung)

p_acf <- p_acf %>%
  #mutate(Hospitalisierung = (Hospitalisierung-m_h)/s_h) %>%
  select(Hospitalisierung) %>%
  ts(frequency = 53, start = c(2020, 1))


p_train <- window(p_acf, end = c(2022,1))
p_test <- window(p_acf, start = c(2022,2))

autoplot(p_acf) + theme_minimal() + ylab("Hospitalization")
# no obvious non-stationarity
acf(p_acf, lag.max = 53)
# strong korrelation up to lag 5
pacf(p_acf)
# using auto.arima for modelidentification
a <- auto.arima(p_acf)
# suggested model: ARIMA(0,1,0)(0,1,0)[53]
png(filename="./Bilder/fc_tuer.png", width= 2000, height = 900)
plot(forecast(a, h = 2), main = "Forecast Thueringen using ARIMA(3,1,0)(0,1,0)[53]")
lines(p_comp)
dev.off()

b <- arima(p_train, order = c(3,1,0), seasonal = list(order = c(0,1,0), period = 53))
accuracy(forecast(b, h = 2), p_test)
```
