---
title: "Phu_Auswertung"
author: 'Phu Nguyen (Matrikelnr: 11904670)'
date: "12/6/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
packages <- c("tidyverse", "gghighlight")
lapply(packages, library, character.only = TRUE)
```


```{r Hospitalisierung mit Jahreszeit}
readRDS('../data_processed/fin_datensatz.Rds')

fin_datensatz$Jahrwoche <- as.character(str_c(fin_datensatz$Kalenderjahr, 
                                              fin_datensatz$Kalenderwoche, sep = " - "))


sum_hosp <- fin_datensatz %>%
  select(Jahrwoche, Hospitalisierung, Jahreszeit) %>%
  group_by(Jahrwoche, Jahreszeit) %>%
  summarise(sum(Hospitalisierung)) %>%
  mutate(Jahreszeit = factor(Jahreszeit, levels = c("Fruehling", "Sommer", "Herbst", "Winter")))

png(filename="./Bilder/Hospitalisierung_mit_Jahreszeit.png", width= 2000, height = 900)

ggplot(data = sum_hosp) +
  geom_col(aes(x = Jahrwoche, y = `sum(Hospitalisierung)`, fill = Jahreszeit)) +
  # geom_vline(xintercept = sum_hosp$Jahrwoche[c(2, seq(16, 94, 13))], color = "#bdbdbd") +
  # geom_vline(xintercept = "2020-18", color = "#bdbdbd") +
  # geom_vline(xintercept = "2020-31", color = "#bdbdbd") +
  # geom_vline(xintercept = "2020-44", color = "#bdbdbd") +
  # geom_vline(xintercept = "2020-52", color = "#bdbdbd") +
  # geom_vline(xintercept = "2021-04", color = "#bdbdbd") +
  # geom_vline(xintercept = "2021-17", color = "#bdbdbd") +
  # geom_vline(xintercept = "2021-30", color = "#bdbdbd") +
  # geom_vline(xintercept = "2021-43", color = "#bdbdbd") +
  scale_x_discrete(breaks = sum_hosp$Jahrwoche[c(1, 52, 98)]) +
  theme_minimal() +
  scale_fill_manual(values = c("#4daf4a","#ffd92f", "#d95f02", "#377eb8")) +
  theme(text = element_text(size = 25)) +
  # theme(legend.position = c(0.95, 0.9),
  #       legend.background = element_rect(fill="white", size=0.5),
  #       axis.text.x = element_text(angle = 45))  +
  ylab("Hospitalisierung")
  

dev.off()
```


```{r Hospitalisierung nach Altersgruppen}
hosp_alter <- fin_datensatz %>%
  select(Jahrwoche, Altersgruppe, Hospitalisierung) %>%
  group_by(Jahrwoche, Altersgruppe) %>%
  summarise(sum(Hospitalisierung))

png(filename="./Bilder/Hospitalisierung_nach_Altersgruppen.png", width= 2000, height = 900)

ggplot(hosp_alter) +
  geom_line(aes(x = Jahrwoche, y = `sum(Hospitalisierung)`, 
                group = Altersgruppe, color = Altersgruppe), size = 1.25) +
  scale_x_discrete(breaks = sum_hosp$Jahrwoche[c(1, 52, 98)]) +
  gghighlight(label_params = list(size = 10)) +
  theme_minimal() +
  scale_color_manual(values = c("#f1a340", "#998ec3")) +
  theme(text = element_text(size = 25)) +
  ylab("Hospitalisierung")

dev.off()
```

```{r Entwicklung Impfquote nach Altersgruppen}
impfquote <- fin_datensatz %>%
  select(Jahrwoche, Impfquote, Altersgruppe, Kalenderwoche) %>%
  group_by(Jahrwoche, Altersgruppe, Kalenderwoche) %>%
  summarise(mean(Impfquote)) %>%
  mutate(Nicht_geimpft = (1 - `mean(Impfquote)`))

impfquote_jung <- impfquote %>%
  filter(Altersgruppe == "00-59") %>%
  mutate(Kalenderwoche = as.integer(Kalenderwoche))
colnames(impfquote_jung)[4] <- "Geimpft"

impfquote_jung %>%
  pivot_longer(!c(Jahrwoche, Altersgruppe, Kalenderwoche), names_to = "Impfstatus", values_to = "Anteil") %>%
  ggplot(aes(x = "", y = Anteil, fill = Impfstatus)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_minimal() +
  theme_void() +
  scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1, labels = c("Geimpft", "Nicht geimpft")) +
  labs(title = "Entwicklung Impfquote bei Jugendlichen") +
  facet_wrap(~ Jahrwoche)

impfquote_alt <- impfquote %>%
  filter(Altersgruppe == "60+") %>%
  mutate(Kalenderwoche = as.integer(Kalenderwoche))
colnames(impfquote_alt)[4] <- "Geimpft"

impfquote_alt %>%
  pivot_longer(!c(Jahrwoche, Altersgruppe, Kalenderwoche), names_to = "Impfstatus", values_to = "Anteil") %>%
  ggplot(aes(x = "", y = Anteil, fill = Impfstatus)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  theme_minimal() +
  theme_void() +
  scale_fill_brewer(type = "seq", palette = "YlGnBu", direction = -1, labels = c("Geimpft", "Nicht geimpft")) +
  labs(title = "Entwicklung Impfquote bei Alten") +
  facet_wrap(~ Jahrwoche)
```

```{r Streudiagramm Neuerkrankung Hospitalisierung}
normal_streu <- ggplot(fin_datensatz) +
  geom_point(aes(x = Neuerkrankung, y = Hospitalisierung, color = Altersgruppe), size = 3) +
  scale_color_manual(values = c("#f1a340", "#998ec3")) +
  theme_minimal() +
  theme(text = element_text(size = 25))

log_streu <- ggplot(fin_datensatz) +
  geom_point(aes(x = log(Neuerkrankung), y = log(Hospitalisierung), color = Altersgruppe), size = 3) +
  scale_color_manual(values = c("#f1a340", "#998ec3")) +
  theme_minimal() +
  theme(text = element_text(size = 25))

png(filename="./Bilder/Scatter_plot.png", width= 2000, height = 900)

ggarrange(normal_streu, log_streu, common.legend = T)

dev.off()
```

```{r Histogramm Hospitalisierung}
png(filename="./Bilder/Histogramm_Hospitalisierung.png", width= 2000, height = 900)

ggplot(final_df_wo_impfung) +
  geom_histogram(aes(x = log(sum_hosp_nowcast + 1), y =..density..), bins = 40, color = "#e34a33", 
                 fill = "#fdbb84") +
  geom_density(aes(x = log(sum_hosp_nowcast + 1))) +
  theme_minimal() +
  xlab("Hospitalisierungen") +
  # ylab("Density") +
  theme(text = element_text(size = 25))

dev.off()
```

NEUE PLOTS

```{r Hospitalisierungsrate Verlauf + Virusvariante}
plot_df <- final_df
plot_df1 <- plot_df %>%
  select(Meldedatum, Neuerkrankung, Hospitalisierung) %>%
  group_by(Meldedatum) %>%
  summarize(sum(Neuerkrankung), sum(Hospitalisierung))
colnames(plot_df1)[c(2,3)] <- c("Neuerkrankung", "Hospitalisierung")
plot_df1 <- plot_df1 %>%
  mutate(Hospitalisierungsrate = Hospitalisierung / Neuerkrankung)

xmax_omikron <- as.Date(max(final_df$Meldedatum))
xmax_alphabeta <- xmin_gamma
xmax_gamma <- xmin_delta
xmax_delta <- xmin_omikron
xmin_alphabeta <- as.Date("2020-12-18")
xmin_gamma <- as.Date("2021-01-11")
xmin_delta <- as.Date("2021-05-11")
xmin_omikron <- as.Date("2021-11-24")

png(filename="./Bilder/Hosprate_Verlauf_Variants.png", width= 2000, height = 900)

ggplot(plot_df1, aes(Meldedatum, Hospitalisierungsrate)) + 
  geom_rect(aes(xmin = xmin_alphabeta, xmax = xmax_alphabeta, ymin = -Inf, ymax = Inf, 
    alpha = I(.01), fill  = I("turquoise"))) +
  annotate("text", label = "Alpha & Beta Variants", x = as.Date("2021-01-11"), y = Inf, angle = 90,
    hjust = 1.1, vjust = -1, size = 10, family = "serif") +
  geom_rect(aes(xmin = xmin_gamma, xmax = xmax_gamma, ymin = -Inf, ymax = Inf, 
    alpha = I(.01), fill  = "orange")) +
  annotate("text", label = "Gamma Variant", x = as.Date("2021-03-23"), y = Inf, angle = 90,
    hjust = 1.1, vjust = -1, size = 10, family = "serif") +
   geom_rect(aes(xmin = xmin_delta, xmax = xmax_delta, ymin = -Inf, ymax = Inf, 
    alpha = I(.01), fill  = I("lawngreen"))) +
  annotate("text", label = "Delta Variant", x = as.Date("2021-08-30"), y = Inf, angle = 90,
    hjust = 1.1, vjust = -1, size = 10, family = "serif") +
  geom_rect(aes(xmin = xmin_omikron, xmax = xmax_omikron, ymin = -Inf, ymax = Inf, 
    alpha = I(.01), fill  = "magenta")) +
  annotate("text", label = "Omicron Variant", x = as.Date("2022-01-07"), y = Inf, angle = 90,
    hjust = 1.1, vjust = -1, size = 10, family = "serif") +
  geom_line(size = 1) +
  theme_minimal() +
  theme(text = element_text(size = 25)) +
  ylim(c(0, 0.5))

dev.off()
```

```{r Anteil Hospitalisierung nach Alter}
plot_df2 <- plot_df %>%
  select(Altersgruppe, Hospitalisierung) %>%
  group_by(Altersgruppe) %>%
  summarise(sum(Hospitalisierung))
colnames(plot_df2)[2] <- "Hospitalisierung"

plot_df2 <- plot_df2 %>%
  mutate(Anteil = round((Hospitalisierung / sum(Hospitalisierung)) * 100, digits = 1))

png(filename="./Bilder/Hosp_Alter.png", width= 2000, height = 900)

ggplot(data = plot_df2, aes(x = Altersgruppe, y = Anteil, fill = Altersgruppe)) +
  geom_col() +
  geom_text(aes(label = Anteil), vjust = -0.3, size = 10) +
  theme_minimal() +
  theme(text = element_text(size = 25),
        legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank()) +
  scale_fill_brewer(palette = "PRGn", direction = -1)

dev.off()
```

```{r}
plot_df3 <- plot_df %>%
  select(Meldedatum, Bundesland, Neuerkrankung, Hospitalisierung) %>%
  group_by(Bundesland, Meldedatum) %>%
  summarise(sum(Neuerkrankung), sum(Hospitalisierung))
colnames(plot_df3)[c(3, 4)] <- c("Neuerkrankung", "Hospitalisierung")

plot_df3 <- plot_df3 %>%
  mutate(Hospitalisierungsrate = Hospitalisierung / Neuerkrankung)

png(filename="./Bilder/Hosp_Verlauf_Bundesland_test.png", width= 2000, height = 900)

plot_df3 %>%
  ggplot() +
  geom_line(aes(x = Meldedatum, y = Hospitalisierungsrate, color = Bundesland), size = 1) +
  gghighlight(label_params = list(size = 10)) +
  theme_minimal() +
  theme(text = element_text(size = 25))

dev.off()

plot_df4 <- plot_df %>%
  select(Meldedatum, Bundesland, Hospitalisierung) %>%
  group_by(Bundesland, Meldedatum) %>%
  summarise(sum(Hospitalisierung))
colnames(plot_df4)[c(3)] <- c("Hospitalisierung")

png(filename="./Bilder/Hosp_Verlauf_Bundesland.png", width= 2000, height = 900)

plot_df4 %>%
  ggplot() +
  geom_line(aes(x = Meldedatum, y = Hospitalisierung, color = Bundesland), size = 1) +
  gghighlight(label_params = list(size = 10)) +
  theme_minimal() +
  theme(text = element_text(size = 25))

dev.off()

plot_df5 <- plot_df %>%
  select(Bundesland, Hospitalisierung, Neuerkrankung) %>%
  group_by(Bundesland) %>%
  summarise(sum(Hospitalisierung), sum(Neuerkrankung))
colnames(plot_df5)[c(2,3)] <- c("Hospitalisierung", "Neuerkrankung")

plot_df5 <- plot_df5 %>%
  mutate(Hospitalisierungsrate = round((Hospitalisierung / Neuerkrankung) * 100, digits = 1))

png(filename="./Bilder/Hosprate_Bundesland.png", width= 2000, height = 900)

plot_df5 %>%
  ggplot(aes(x = Bundesland, y = Hospitalisierungsrate, fill = Bundesland)) +
  geom_col() +
  geom_text(aes(label = Hospitalisierungsrate), vjust = -0.3, size = 10) +
  scale_x_discrete(labels = c("Baden-Wuerttemberg" = "BW",
                              "Bayern" = "BY",
                              "Berlin" = "BE",
                              "Brandenburg" = "BB",
                              "Bremen" = "HB",
                              "Hamburg" = "HH",
                              "Hessen" = "HE",
                              "Mecklenburg-Vorpommern" = "MV",
                              "Niedersachsen" = "NI",
                              "Nordrhein-Westfalen" = "NW",
                              "Rheinland-Pfalz" = "RP",
                              "Saarland" = "SL",
                              "Sachsen" = "SN",
                              "Sachsen-Anhalt" = "ST",
                              "Schleswig-Holstein" = "SH",
                              "Thueringen" = "TH")) +
  theme_minimal() +
  theme(text = element_text(size = 25),
        legend.position = "none",
        panel.grid = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank()) +
  scale_fill_manual(values = mycolors)

dev.off()

mycolors <- colorRampPalette(brewer.pal(12, "Paired"))(16)
 
ggplot(mtcars) + 
  geom_histogram(aes(factor(hp)), fill=getPalette(16)) + 
  theme(legend.position="right")
```

