---
title: "test"
author: "Alexander Marquard / 11779957"
date: "4 3 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(feasts)
library(gridExtra)
library(mgcv)
library(forecast)
library(marima)
library(tseries)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")
impfungen <- readRDS("../../data_truth/RKI/impfungen.Rds")

N <- sum(unique(final_df$population))

all <- final_df %>%
  filter(Meldedatum >= "2021-01-01")
```

```{r}
res_mods <- list()
bls <- list()
for (i in unique(final_df$Bundesland)) {
  bl_a <- all %>%
  filter(Bundesland == i) %>%
  mutate(Bundesland = as.factor(Bundesland)) %>%
  group_by(Meldedatum) %>%
  summarise(Hospitalisierung = sum(Hospitalisierung),
            Neuerkrankung = sum(Neuerkrankung),
            population = sum(population)) %>%
  mutate(hosprate = Hospitalisierung/population * 100000,
         neurate = Neuerkrankung/population * 100000) %>%
  mutate(rate = Hospitalisierung/Neuerkrankung) %>%
  mutate(index = row_number(Meldedatum)) %>%
  select(Meldedatum, index, Hospitalisierung, Neuerkrankung, hosprate, neurate, rate)

  # Beschränken auf Zeitraum bis 20.02,
  # somit nutzen wir definitiv aktuelle Daten
  bl_a <- bl_a %>% filter(Meldedatum <= "2022-02-20")
  bl <- bl_a %>% select(hosprate) %>% ts()
  bls[[i]] <- bl
  
  res_mods[[i]] <- auto.arima(bl)
}

for (i in seq_along(res_mods)) {
  print(names(res_mods)[i])
  print(res_mods[names(res_mods)[i]])
}

```

```{r Bayern}
res_mods$Bayern
bay <- bls$Bayern
order <- c(2,1,1)

# Plot for Bayern
png("./Bilder/bay_ts.png", width = 2000, height = 900)
autoplot(bay) + xlab("Zeit") + ylab("Hospitalisierungsrate") + 
  theme_minimal() +
  theme(text = element_text(size = 25))
dev.off()

# forecast function for tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(bay, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(bay, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(bay, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(bay, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))

# forecasting for complete time
fc_res <- ts(matrix(NA_real_, nrow = 48, ncol = 1))
for (i in seq(1, 48)) {
  train <- window(bay, start = i, end = 11 + i)
  fc <- try(forecast(Arima(train, order = order), h = 1), silent = T)
  if (!is.element("try-error", class(fc))) {
      fc_res[i, ] <- fc$mean[1]
  }
}

png("./Bilder/bay_fc_all.png", width = 2000, height = 900)
par(cex.lab = 2, cex.axis = 2)
plot(bay, xlab = "Zeit", ylab = "Hospitalisierungsrate", col = "black", 
     cex = 2)
lines(x = seq(13,60), y= as.numeric(fc_res), type = "p", col = "red", cex = 2)
legend(0, 20, legend=c("Tatsächlich", "Geschätzt"),
       col=c("black", "red"), lty=1, cex=2)
dev.off()


# forecast 20.02.22
train <- window(bay, start = 48, end = 59)
test <- window(bay, start = 60, end = 60)
ar_best <- Arima(train, order = order)
fc_a <- forecast(ar_best, h = 1)
accuracy(fc_a, test)

plot(fc_a$x, type = "l", xlim = c(30,62), 
     main = "Punktschätzer für eine Woche", ylab = "Hospitalisierungsrate", xlab = "Zeit")
lines(fc_a$mean, col = "blue", type = "p")
lines(x = c(60), y = test, type = "p", col = "red")
legend(30,15, legend = c("Tatsächlich", "Geschätzt"), col = c("red", "blue"), lty = 1, cex = 0.8)

# diagnosis
checkresiduals(ar_best)



##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(bay, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(bay, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(bay, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(bay, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting for hole time
fc_res <- ts(matrix(NA_real_, nrow = 47, ncol = 2))
for (i in seq(1, 47)) {
  train <- window(bay, start = i, end = 11 + i)
  fc <- try(forecast(Arima(train, order = order), h = 2), silent = T)
  if (!is.element("try-error", class(fc))) {
      fc_res[i, ] <- fc$mean[seq(2)]
  }
}

png("./Bilder/bay_fc_all_two week.png", width = 2000, height = 900)
par(cex.lab = 2, cex.axis = 2)
plot(bay, xlab = "Zeit", ylab = "Hospitalisierungsrate", col = "black", 
     cex = 2)
lines(x = seq(14,60), y= as.numeric(fc_res[,2]), type = "p", col = "orange", cex = 2)
legend(0, 20, legend=c("Tatsächlich", "Geschätzt"),
       col=c("black", "orange"), lty=1, cex=2)
dev.off()


# forecasting of 20.02.22
train <- window(bay, start = 47, end = 58)
test <- window(bay, start = 59, end = 60)
ar_best <- Arima(train, order = c(2,1,1))
fc_a2 <- forecast(ar_best, h = 2)
accuracy(fc_a2, test)

plot(fc_a2$x, type = "l", xlim = c(30,62), 
     main = "Punktschätzer für zwei Wochen", ylab = "Hospitalisierungsrate", xlab = "Zeit")
lines(x = 60, y = fc_a2$mean[2], col = "blue", type = "p")
lines(x = c(60), y = test[2], type = "p", col = "red")
legend(30,15, legend = c("Tatsächlich", "Geschätzt"), col = c("red", "blue"), lty = 1, cex = 0.8)
checkresiduals(ar_best)


##################
# Forecast for 27.02 and 03.04
#################

(train <- window(bay, start = 49, end = 60))
(ar_best <- Arima(train, order = order))
(fc_a3 <- forecast(ar_best, h = 2))

plot(fc_a3$x, type = "l", xlim = c(30,62), 
     main = "Punktschätzer für eine und zwei Wochen", ylab = "Hospitalisierungsrate", xlab = "Zeit")
lines(x = c(61,62), y = fc_a3$mean, col = "blue", type = "p")
legend(30,15, legend = c("Geschätzt"), col = c("blue"), lty = 1, cex = 0.8)
checkresiduals(ar_best)
```


```{r Baden-wuerttemberg}
res_mods$`Baden-Wuerttemberg`
bw <- bls$`Baden-Wuerttemberg`
order <- c(0,1,2)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(bw, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(bw, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(bw, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(bw, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(bw, start = 40, end = 59)
test <- window(bw, start = 60, end = 60)
ar_best <- Arima(train, order = order)
(fc_bw <- forecast(ar_best, h = 1))
accuracy(fc_bw, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(bw, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(bw, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(bw, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(bw, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(bw, start = 39, end = 58)
test <- window(bw, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_bw2 <- forecast(ar_best, h = 2))
accuracy(fc_bw2, test)

checkresiduals(ar_best)
```
```{r Berlin}
res_mods$Berlin
ber <- bls$Berlin
order <- c(0,1,0)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(ber, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(ber, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(ber, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(ber, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(ber, start = 36, end = 59)
(test <- window(ber, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_ber <- forecast(ar_best, h = 1))
accuracy(fc_ber, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(ber, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(ber, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(ber, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(ber, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(ber, start = 35, end = 58)
test <- window(ber, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_ber2 <- forecast(ar_best, h = 2))
accuracy(fc_ber2, test)

checkresiduals(ar_best)
```

```{r Brandenburg}
res_mods$Brandenburg
bra <- bls$Brandenburg
order <- c(1,2,1)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(bra, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(bra, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(bra, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(bra, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(bra, start = 48, end = 59)
(test <- window(bra, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_bra <- forecast(ar_best, h = 1))
accuracy(fc_bra, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(bra, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(bra, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(bra, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(bra, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(bra, start = 47, end = 58)
test <- window(bra, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_bra2 <- forecast(ar_best, h = 2))
accuracy(fc_bra2, test)

checkresiduals(ar_best)
```

```{r Bremen}
res_mods$Bremen
bre <- bls$Bremen
order <- c(2,0,0)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(bre, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(bre, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(bre, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(bre, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(bre, start = 36, end = 59)
(test <- window(bre, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_bre <- forecast(ar_best, h = 1))
accuracy(fc_bre, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(bre, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(bre, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(bre, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(bre, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(bre, start = 35, end = 58)
test <- window(bre, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_bre2 <- forecast(ar_best, h = 2))
accuracy(fc_bre2, test)

checkresiduals(ar_best)
```

```{r Hamburg}
res_mods$Hamburg
ha <- bls$Hamburg
order <- c(0,1,1)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(ha, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(ha, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(ha, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(ha, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(ha, start = 40, end = 59)
(test <- window(ha, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_ha <- forecast(ar_best, h = 1))
accuracy(fc_ha, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(ha, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(ha, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(ha, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(ha, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(ha, start = 47, end = 58)
test <- window(ha, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_ha2 <- forecast(ar_best, h = 2))
accuracy(fc_ha2, test)

checkresiduals(ar_best)
```

```{r Hessen}
res_mods$Hessen
hes <- bls$Hessen
order <- c(1,2,0)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(hes, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(hes, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(hes, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(hes, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(hes, start = 40, end = 59)
(test <- window(hes, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_hes <- forecast(ar_best, h = 1))
accuracy(fc_hes, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(hes, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(hes, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(hes, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(hes, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(hes, start = 39, end = 58)
test <- window(hes, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_hes2 <- forecast(ar_best, h = 2))
accuracy(fc_hes2, test)

checkresiduals(ar_best)
```

```{r Mecklenburg-Vorpommern}
res_mods$`Mecklenburg-Vorpommern`
mv <- bls$`Mecklenburg-Vorpommern`
order <- c(3,2,1)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(mv, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(mv, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(mv, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(mv, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(mv, start = 44, end = 59)
(test <- window(mv, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_mv <- forecast(ar_best, h = 1))
accuracy(fc_mv, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(mv, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(mv, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(mv, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(mv, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(mv, start = 43, end = 58)
test <- window(mv, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_mv2 <- forecast(ar_best, h = 2))
accuracy(fc_mv2, test)

checkresiduals(ar_best)
```

```{r Niedersachsen}
res_mods$Niedersachsen
ns <- bls$Niedersachsen
order <- c(1,1,0)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(ns, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(ns, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(ns, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(ns, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(ns, start = 40, end = 59)
(test <- window(ns, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_ns <- forecast(ar_best, h = 1))
accuracy(fc_ns, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(ns, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(ns, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(ns, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(ns, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(ns, start = 39, end = 58)
test <- window(ns, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_ns2 <- forecast(ar_best, h = 2))
accuracy(fc_ns2, test)

checkresiduals(ar_best)
```

```{r Nordrhein-Westfalen}
res_mods$`Nordrhein-Westfalen`
nrw <- bls$`Nordrhein-Westfalen`
order <- c(2,1,2)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(nrw, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(nrw, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(nrw, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(nrw, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(nrw, start = 36, end = 59)
(test <- window(nrw, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_nrw <- forecast(ar_best, h = 1))
accuracy(fc_nrw, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(nrw, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(nrw, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(nrw, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(nrw, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(nrw, start = 35, end = 58)
test <- window(nrw, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_nrw2 <- forecast(ar_best, h = 2))
accuracy(fc_nrw2, test)

checkresiduals(ar_best)
```

```{r Rheinland-Pfalz}
res_mods$`Rheinland-Pfalz`
rp <- bls$`Rheinland-Pfalz`
order <- c(0,1,3)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(rp, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(rp, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(rp, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(rp, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(rp, start = 48, end = 59)
(test <- window(rp, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_rp <- forecast(ar_best, h = 1))
accuracy(fc_rp, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(rp, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(rp, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(rp, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(rp, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(rp, start = 39, end = 58)
test <- window(rp, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_rp2 <- forecast(ar_best, h = 2))
accuracy(fc_rp2, test)

checkresiduals(ar_best)
```

```{r Saarland}
res_mods$Saarland
sl <- bls$Saarland
order <- c(1,1,1)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(sl, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(sl, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(sl, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(sl, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(sl, start = 48, end = 59)
(test <- window(sl, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_sl <- forecast(ar_best, h = 1))
accuracy(fc_sl, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(sl, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(sl, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(sl, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(sl, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(sl, start = 47, end = 58)
test <- window(sl, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_sl2 <- forecast(ar_best, h = 2))
accuracy(fc_sl2, test)

checkresiduals(ar_best)
```

```{r Sachsen}
res_mods$Sachsen
sa <- bls$Sachsen
order <- c(2,0,3)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(sa, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(sa, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(sa, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(sa, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(sa, start = 48, end = 59)
(test <- window(sa, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_sa <- forecast(ar_best, h = 1))
accuracy(fc_sa, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(sa, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(sa, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(sa, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(sa, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(sa, start = 47, end = 58)
test <- window(sa, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_sa2 <- forecast(ar_best, h = 2))
accuracy(fc_sa2, test)

checkresiduals(ar_best)
```

```{r Sachsen-Anhalt}
res_mods$`Sachsen-Anhalt`
saa <- bls$`Sachsen-Anhalt`
order <- c(1,1,0)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(saa, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(saa, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(saa, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(saa, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(saa, start = 36, end = 59)
(test <- window(saa, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_saa <- forecast(ar_best, h = 1))
accuracy(fc_saa, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(saa, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(saa, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(saa, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(saa, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(saa, start = 35, end = 58)
test <- window(saa, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_saa2 <- forecast(ar_best, h = 2))
accuracy(fc_saa2, test)

checkresiduals(ar_best)
```

```{r Schleswig-Holstein}
res_mods$`Schleswig-Holstein`
sh <- bls$`Schleswig-Holstein`
order <- c(1,2,1)

# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(sh, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(sh, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(sh, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(sh, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(sh, start = 48, end = 59)
(test <- window(sh, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_sh <- forecast(ar_best, h = 1))
accuracy(fc_sh, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(sh, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(sh, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(sh, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(sh, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(sh, start = 43, end = 58)
test <- window(sh, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_sh2 <- forecast(ar_best, h = 2))
accuracy(fc_sh2, test)

checkresiduals(ar_best)
```

```{r Thueringen}
res_mods$Thueringen
th <- bls$Thueringen
order <- c(2,0,2)

# thüringen isn´t working

th_ <- diff(th)
auto.arima(th_)
# -> Use slightly adjusted order 2,1,0
order <- c(2,1,0)


# forecast function für tsCV
fc_fct <-  function(x, h) { 
  forecast(Arima(x, order = order), h = h)
}

# gliding window evaluation
e_12 <- tsCV(th, forecastfunction = fc_fct, h = 1, initial = 0, window = 12)
e_16 <- tsCV(th, forecastfunction = fc_fct, h = 1, initial = 0, window = 16)
e_20 <- tsCV(th, forecastfunction = fc_fct, h = 1, initial = 0, window = 20)
e_24 <- tsCV(th, forecastfunction = fc_fct, h = 1, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecast 20.02.22
train <- window(th, start = 48, end = 59)
(test <- window(th, start = 60, end = 60))
ar_best <- Arima(train, order = order)
(fc_th <- forecast(ar_best, h = 1))
accuracy(fc_th, test)

# diagnosis
checkresiduals(ar_best)


##################
# Two weeks
#################

# gliding window evaluation
e_12 <- tsCV(th, forecastfunction = fc_fct, h = 2, initial = 0, window = 12)
e_16 <- tsCV(th, forecastfunction = fc_fct, h = 2, initial = 0, window = 16)
e_20 <- tsCV(th, forecastfunction = fc_fct, h = 2, initial = 0, window = 20)
e_24 <- tsCV(th, forecastfunction = fc_fct, h = 2, initial = 0, window = 24)

sqrt(mean(e_12^2, na.rm = T))
sqrt(mean(e_16^2, na.rm = T))
sqrt(mean(e_20^2, na.rm = T))
sqrt(mean(e_24^2, na.rm = T))


# forecasting of 20.02.22
train <- window(th, start = 47, end = 58)
test <- window(th, start = 59, end = 60)
ar_best <- Arima(train, order = order)
(fc_th2 <- forecast(ar_best, h = 2))
accuracy(fc_th2, test)

checkresiduals(ar_best)
```


```{r germany}
fc_oneweek <- c(fc_a$mean,
fc_ber$mean,
fc_bra$mean,
fc_bre$mean,
fc_bw$mean,
fc_ha$mean,
fc_hes$mean,
fc_mv$mean,
fc_nrw$mean,
fc_ns$mean,
fc_rp$mean,
fc_sl$mean,
fc_sa$mean,
fc_saa$mean,
fc_sh$mean,
fc_th$mean)

names_fc_oneweek <- c("Bayern", "Berlin", "Brandenburg", "Bremen",
                        "Baden-Wuerttemberg", "Hamburg", "Hessen",
                        "Mecklenburg-Vorpommern", "Nordrhein-Westfalen",
                        "Niedersachsen", "Rheinland-Pfalz", "Saarland", "Sachsen",
                        "Sachsen-Anhalt", "Schleswig-Holstein",
                        "Thueringen")

fc_twoweek <- c(fc_a2$mean[2],
fc_ber2$mean[2],
fc_bra2$mean[2],
fc_bre2$mean[2],
fc_bw2$mean[2],
fc_ha2$mean[2],
fc_hes2$mean[2],
fc_mv2$mean[2],
fc_nrw2$mean[2],
fc_ns2$mean[2],
fc_rp2$mean[2],
fc_sl2$mean[2],
fc_sa2$mean[2],
fc_saa2$mean[2],
fc_sh2$mean[2],
fc_th2$mean[2])

# names_fc_twoweek <- c("Bayern", "Berlin", "Brandenburg", "Bremen",
#                        "Baden-Wuerttemberg", "Hamburg", "Hessen",
#                        "Mecklenburg-Vorpommern", "Nordrhein-Westfalen",
#                        "Niedersachsen", "Rheinland-Pfalz", "Saarland", "Sachsen",
#                        "Sachsen-Anhalt", "Schleswig-Holstein",
#                        "Thueringen")

germany_res <- data.frame("oneweek" = fc_oneweek, "twoweek" = fc_twoweek, 
                          "Bundesland" = names_fc_oneweek, 
                          Meldedatum = as.Date("2022-02-20", format ="%Y-%m-%d"))

hosp_germ <- all %>%
  group_by(Meldedatum, Bundesland) %>% filter(Meldedatum <= "2022-02-20") %>%
  summarise(Hospitalisierung = sum(Hospitalisierung),
            population = sum(population))

p_df <- right_join(germany_res, hosp_germ) %>% group_by(Bundesland) %>%
  mutate(hosprate = Hospitalisierung/population * 100000)

ggplot(p_df) +
  geom_line(aes(x = Meldedatum, y = hosprate, col = "True")) +
  geom_point(aes(x = Meldedatum, y = oneweek, col = "1 Woche Vorhersage")) +
  geom_point(aes(x = Meldedatum, y = twoweek, col = "2 Wochen Vorhersage")) +
  facet_wrap(~Bundesland) +
  scale_color_manual(values = c("True" = "black", "1 Woche Vorhersage" = "red", 
                                "2 Wochen Vorhersage" = "blue"),
                     name = c("Legende")) +
  ylab("Hospitalisierungsrate") +
  theme_minimal()

p_df2 <- p_df %>%
  mutate(hosp_ow = oneweek/100000 * population,
         hosp_tw = twoweek/100000 * population) %>%
  group_by(Meldedatum) %>%
  summarise(hosp = sum(Hospitalisierung),
            population = sum(population),
            hosp_ow = sum(hosp_ow),
            hosp_tw = sum(hosp_tw)) %>%
  mutate(hosprate = hosp/population * 100000,
         hosp_ow_r = hosp_ow/population * 100000,
         hosp_tw_r = hosp_tw/population * 100000)
  
ggplot(p_df2) +
  geom_line(aes(x = Meldedatum, y = hosprate)) +
  geom_point(aes(x = Meldedatum, y = hosp_ow_r)) +
  geom_point(aes(x = Meldedatum, y = hosp_tw_r)) +
  theme_minimal()
```
