---
title: "allBW"
author: "Alexander Marquard / 11779957"
date: "1/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(mgcv)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")

## Erstelle Liste mit Datensatz zu jedem Bundesland
list_of_dfs <- split(final_df, as.factor(final_df$Bundesland))
```

```{r boxplots}
lapply(list_of_dfs, function(x) {
  plot(x$Altersgruppe, log(x$Hospitalisierung + 1), 
       main = unique(x$Bundesland),
       ylab = "log(Hospitalisiert)",
       xlab = "Altersgruppen")
})
```

```{r agegroups}
# Passe Altersgruppen an:

## Baden-Württemberg ####
# Nichts zu tun

## Bayern ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 sowie 
# 35-69, 60-79 und 80+ zusammengeführt werden
levels(list_of_dfs$Bayern$Altersgruppe) <- c("00-14", "00-14", "15-34", "35+","35+","35+")

list_of_dfs$Bayern <- list_of_dfs$Bayern %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$Bayern <- list_of_dfs$Bayern %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Berlin ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 zusammengeführt erden
levels(list_of_dfs$Berlin$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60-79","80+")

list_of_dfs$Berlin <- list_of_dfs$Berlin %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$Berlin <- list_of_dfs$Berlin %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Brandenburg ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 zusammengeführt werden
levels(list_of_dfs$Brandenburg$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60-79","80+")

list_of_dfs$Brandenburg <- list_of_dfs$Brandenburg %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
## Ergänze indizes

list_of_dfs$Brandenburg <- list_of_dfs$Brandenburg %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Bremen ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14, 35-59 und 60-79 zusammengeführt werden
levels(list_of_dfs$Bremen$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-79","35-79","80+")

list_of_dfs$Bremen <- list_of_dfs$Bremen %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
## Ergänze indizes

list_of_dfs$Bremen <- list_of_dfs$Bremen %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Hamburg ####

# Ausgehend von den Altersboxplots können die Gruppen 35-59 und 60-79 zusammengeführt werden
levels(list_of_dfs$Hamburg$Altersgruppe) <- c("00-04", "05-14", "15-34", "35-79","35-79","80+")

list_of_dfs$Hamburg <- list_of_dfs$Hamburg %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
## Ergänze indizes

list_of_dfs$Hamburg <- list_of_dfs$Hamburg %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

## Hessen ####
# Nichts zu tun


## Mecklenburg-Vorpommern #### 

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14, 35-59 und 60-79 zusammengeführt werden
levels(list_of_dfs$`Mecklenburg-Vorpommern`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-79","35-79","80+")

list_of_dfs$`Mecklenburg-Vorpommern` <- list_of_dfs$`Mecklenburg-Vorpommern` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
## Ergänze indizes

list_of_dfs$`Mecklenburg-Vorpommern` <- list_of_dfs$`Mecklenburg-Vorpommern` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

## Niedersachsen ####
# Nichts zu tun


## Nordrhein-Westfalen

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14
levels(list_of_dfs$`Nordrhein-Westfalen`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60-79","80+")

list_of_dfs$`Nordrhein-Westfalen` <- list_of_dfs$`Nordrhein-Westfalen` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$`Nordrhein-Westfalen` <- list_of_dfs$`Nordrhein-Westfalen` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

## Rheinland-Pfalz

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 zusammengelegt werden 
levels(list_of_dfs$`Rheinland-Pfalz`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60-79","80+")

list_of_dfs$`Rheinland-Pfalz` <- list_of_dfs$`Rheinland-Pfalz` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$`Rheinland-Pfalz` <- list_of_dfs$`Rheinland-Pfalz` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

## Saarland ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 entfernt werden
list_of_dfs$Saarland <- list_of_dfs$Saarland %>%
  filter(!(Altersgruppe %in% c("00-04","05-14")))

## Ergänze indizes

list_of_dfs$Saarland <- list_of_dfs$Saarland %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Sachsen ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 
levels(list_of_dfs$Sachsen$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60-79","80+")

list_of_dfs$Sachsen <- list_of_dfs$Sachsen %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$Sachsen <- list_of_dfs$Sachsen %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Sachsen-Anhalt ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14
levels(list_of_dfs$`Sachsen-Anhalt`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35+","35+","35+")

list_of_dfs$`Sachsen-Anhalt` <- list_of_dfs$`Sachsen-Anhalt` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$`Sachsen-Anhalt` <- list_of_dfs$`Sachsen-Anhalt` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Schleswig-Holstein ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 sowie 
# 35-69, 60-79 zusammengeführt werden
levels(list_of_dfs$`Schleswig-Holstein`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-79","35-79","80+")

list_of_dfs$`Schleswig-Holstein` <- list_of_dfs$`Schleswig-Holstein` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$`Schleswig-Holstein` <- list_of_dfs$`Schleswig-Holstein` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))


## Thueringen ####

# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14 sowie 
# 60-79 und 80+ zusammengeführt werden
levels(list_of_dfs$Thueringen$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-59","60+","60+")

list_of_dfs$Thueringen <- list_of_dfs$Thueringen %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

## Ergänze indizes

list_of_dfs$Thueringen <- list_of_dfs$Thueringen %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))
```
```{r test und train df}
############################################################
# schließe letzen Monat aus für Modell. Aktuell die Daten:
# - 24.01
# - 17.01
# - 10.01
# - 03.01

# Forecaste die Daten:
# - 03.01
# - 10.01
############################################################

# list_of_dfs wird letzter Monat gefiltert
train_list <- list()
lapply(names(list_of_dfs), function(x) {
  train_list[[x]] <<- list_of_dfs[[x]] %>%
    filter(!(Meldedatum %in% c(as.Date("2022-01-03"), as.Date("2022-01-10"), 
                               as.Date("2022-01-17"), as.Date("2022-01-24"))))
})


## forecast bundesland
true_bl <- list()
lapply(names(list_of_dfs), function(x) {
  true_bl[[x]] <<- list_of_dfs[[x]] %>%
    filter(Meldedatum %in% c(as.Date("2022-01-03"), as.Date("2022-01-10"))) %>%
    group_by(Meldedatum) %>% 
    summarise(sum(Hospitalisierung))
})


## forecast bundesland, Altersgruppe
true_bl_age <- list()
lapply(names(list_of_dfs), function(x) {
  true_bl_age[[x]] <<- list_of_dfs[[x]] %>%
    filter(Meldedatum <= as.Date("2022-01-10")) %>%
    group_by(Meldedatum, Altersgruppe)
})


## true total
true_total <- data.frame()
true_total <- list_of_dfs$`Baden-Wuerttemberg`
for (i in names(list_of_dfs)[-1]) {
  true_total <- true_total %>% bind_rows(list_of_dfs[[i]])
}
true_total <- true_total %>%
  filter(Meldedatum <= as.Date("2022-01-10")) %>%
  group_by(Meldedatum) %>%
  summarise(sum(Hospitalisierung))
```

```{r all}

bl_models <- list()
for (i in seq_along(train_list)) {
  bl_name <- names(train_list)[[i]]
  bl_models[[bl_name]] <- list()
}

# knots Bawü
bl_models$`Baden-Wuerttemberg`[["k"]][["s_index"]] <- 90
bl_models$`Baden-Wuerttemberg`[["k"]][["s_KW"]] <- 30
bl_models$`Baden-Wuerttemberg`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Baden-Wuerttemberg`[["dist"]] <- "nb"

# knots Bayern
bl_models$Bayern[["k"]][["s_index"]] <- 90
bl_models$Bayern[["k"]][["s_KW"]] <- 30
bl_models$Bayern[["k"]][["s_index_by_AG"]] <- 30
bl_models$Bayern[["dist"]] <- "nb"

# knots Berlin
bl_models$Berlin[["k"]][["s_index"]] <- 90
bl_models$Berlin[["k"]][["s_KW"]] <- 30
bl_models$Berlin[["k"]][["s_index_by_AG"]] <- 30
bl_models$Berlin[["dist"]] <- "nb"

# knots Brandenburg (Qian)
bl_models$Brandenburg[["k"]][["s_index"]] <- 90
bl_models$Brandenburg[["k"]][["s_KW"]] <- 30
bl_models$Brandenburg[["k"]][["s_index_by_AG"]] <- 30
bl_models$Brandenburg[["dist"]] <- "nb"

# knots Bremen
bl_models$Bremen[["k"]][["s_index"]] <- 90
bl_models$Bremen[["k"]][["s_KW"]] <- 30
bl_models$Bremen[["k"]][["s_index_by_AG"]] <- 30
bl_models$Bremen[["dist"]] <- "nb"

# knots Hamburg
bl_models$Hamburg[["k"]][["s_index"]] <- 90
bl_models$Hamburg[["k"]][["s_KW"]] <- 30
bl_models$Hamburg[["k"]][["s_index_by_AG"]] <- 30
bl_models$Hamburg[["dist"]] <- "nb"

# knots Hessen
bl_models$Hessen[["k"]][["s_index"]] <- 90
bl_models$Hessen[["k"]][["s_KW"]] <- 30
bl_models$Hessen[["k"]][["s_index_by_AG"]] <- 30
bl_models$Hessen[["dist"]] <- "nb"

# knots Mecklenburg-V
bl_models$`Mecklenburg-Vorpommern`[["k"]][["s_index"]] <- 90
bl_models$`Mecklenburg-Vorpommern`[["k"]][["s_KW"]] <- 30
bl_models$`Mecklenburg-Vorpommern`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Mecklenburg-Vorpommern`[["dist"]] <- "poisson"

# knots Niedersachsen

bl_models$Niedersachsen[["k"]][["s_index"]] <- 90
bl_models$Niedersachsen[["k"]][["s_KW"]] <- 30
bl_models$Niedersachsen[["k"]][["s_index_by_AG"]] <- 30
bl_models$Niedersachsen[["dist"]] <- "poisson"

# knots Nordrhein-Westfalen

bl_models$`Nordrhein-Westfalen`[["k"]][["s_index"]] <- 90
bl_models$`Nordrhein-Westfalen`[["k"]][["s_KW"]] <- 30
bl_models$`Nordrhein-Westfalen`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Nordrhein-Westfalen`[["dist"]] <- "poisson"

# knots Rheinland-Pf
bl_models$`Rheinland-Pfalz`[["k"]][["s_index"]] <- 90
bl_models$`Rheinland-Pfalz`[["k"]][["s_KW"]] <- 30
bl_models$`Rheinland-Pfalz`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Rheinland-Pfalz`[["dist"]] <- "poisson"

# Saarland bisher am schlechtesten
# knots Saarland
bl_models$Saarland[["k"]][["s_index"]] <- 90
bl_models$Saarland[["k"]][["s_KW"]] <- 30
bl_models$Saarland[["k"]][["s_index_by_AG"]] <- 30
bl_models$Saarland[["dist"]] <- "poisson"

# knots Sachsen
bl_models$Sachsen[["k"]][["s_index"]] <- 90
bl_models$Sachsen[["k"]][["s_KW"]] <- 30
bl_models$Sachsen[["k"]][["s_index_by_AG"]] <- 30
bl_models$Sachsen[["dist"]] <- "poisson"

# nb hat bessere Residual-Verteilung
# knots Sachsen-Anhalt
bl_models$`Sachsen-Anhalt`[["k"]][["s_index"]] <- 90
bl_models$`Sachsen-Anhalt`[["k"]][["s_KW"]] <- 30
bl_models$`Sachsen-Anhalt`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Sachsen-Anhalt`[["dist"]] <- "nb"

# knots Schleswig-Holstein
bl_models$`Schleswig-Holstein`[["k"]][["s_index"]] <- 90
bl_models$`Schleswig-Holstein`[["k"]][["s_KW"]] <- 30
bl_models$`Schleswig-Holstein`[["k"]][["s_index_by_AG"]] <- 30
bl_models$`Schleswig-Holstein`[["dist"]] <- "poisson"

# knots Thueringen
bl_models$Thueringen[["k"]][["s_index"]] <- 90
bl_models$Thueringen[["k"]][["s_KW"]] <- 30
bl_models$Thueringen[["k"]][["s_index_by_AG"]] <- 30
bl_models$Thueringen[["dist"]] <- "poisson"

```

```{r model}

## Nur ene Vertielung benutzen oder Argumentieren
# Entscheidung sauber begründen

for (i in seq_along(list_of_dfs)) {
  bl_name <- names(list_of_dfs)[[i]]
  bl_models[[bl_name]][["model"]] <- gam(Hospitalisierung ~ Neuerkrankung * Altersgruppe +
                               s(index, bs = "ps", k = bl_models[[bl_name]][["k"]][["s_index"]]) + 
                               s(Kalenderwoche, bs = "cc", k = bl_models[[bl_name]][["k"]][["s_KW"]]) +
                               s(index, bs = "ps", by = Altersgruppe, k = bl_models[[bl_name]][["k"]][["s_index_by_AG"]]),
                             data = train_list[[i]],
                             method = "REML",
                             family = bl_models[[bl_name]][["dist"]],
                             knots = list(Kalenderwoche = c(0.5, 53.5)))
}
```

```{r forecast}
pdata <- list()
for (i in names(bl_models)) {
  pdata[[i]] <- true_bl_age[[i]]
  pdata[[i]] <- cbind(pdata[[i]], predict(bl_models[[i]][["model"]], 
                                          true_bl_age[[i]], type = "response", se = T))
  pdata[[i]] <- transform(pdata[[i]], upr = fit + 2 * se.fit, 
                          lwr = fit - 2 * se.fit)
}

# forecast für jedes Bundesland:
ggplot() +
  geom_line(data = pdata$`Rheinland-Pfalz`, aes(x = Meldedatum, y = Hospitalisierung, col = Altersgruppe), alpha = 0.5) +
  #scale_color_manual(values=c("#ff0000", "#56ff00", "#000fff")) +
  geom_point(data = 
               pdata$`Rheinland-Pfalz`[pdata$`Rheinland-Pfalz`$Meldedatum %in% c(as.Date("2022-01-03"), 
                                                           as.Date("2022-01-10")),], 
             aes(x = Meldedatum, y = fit, col = Altersgruppe)) +
  geom_vline(xintercept = as.Date("2021-12-27")) + theme_minimal()

# forecast insgesamt
forecast_df <- true_total
t <- lapply(pdata, function(x){
  x %>% group_by(Meldedatum) %>% summarise(sum(fit)) %>% select(`sum(fit)`)
})
tm <- matrix(unlist(t), ncol = 16, byrow = F)
# Jede Spalte ist ein Bundesland
# Jede Zeile ist eine KW
tmp <- rowSums(tm)

forecast_df <- cbind(forecast_df, tmp)
ggplot(forecast_df) +
  geom_line(aes(x = Meldedatum, y = `sum(Hospitalisierung)`), col = "black") +
  geom_line(aes(x = Meldedatum, y = tmp), col = "red") +
  geom_vline(xintercept = as.Date("2021-12-27")) +
  theme_minimal()



# Über das Alter:

bay_allAge <- true_bl_age$Bayern %>%
  group_by(Meldedatum) %>%
  summarise(sum(Hospitalisierung))

fit_bay <- pdata$Bayern %>%
  group_by(Meldedatum) %>%
  summarise(sum(fit))

temp_final <- cbind(bay_allAge, tmp = fit_bay$`sum(fit)`)

ggplot(temp_final) +
  geom_line(aes(x = Meldedatum, y = `sum(Hospitalisierung)`), col = "black") +
  geom_line(aes(x = Meldedatum, y = tmp), col ="red") +
  geom_vline(xintercept = as.Date("2021-12-27")) +
  theme_minimal()
```