---
title: "allBW"
author: "Alexander Marquard / 11779957"
date: "1/30/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(mgcv)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")

## Erstelle List mit Datensatz zu jedem Bundesland
list_of_dfs <- split(final_df, as.factor(final_df$Bundesland))
# bawü <- dplyr::filter(final_df, Bundesland == "Baden-Württemberg")
```

```{r boxplots}
lapply(list_of_dfs, function(x) {
  plot(x$Altersgruppe, log(x$Hospitalisierung + 1), 
       main = unique(x$Bundesland),
       ylab = "log(Hospitalisiert)",
       xlab = "Altersgruppen")
})
```

```{r all}

bl_models <- list()
for (i in seq_along(list_of_dfs)) {
  bl_name <- names(list_of_dfs)[[i]]
  bl_models[[bl_name]] <- list()
}
for (i in seq_along(bl_models)) {
  bl_models[[i]][["k"]][["s_index"]] <- 90
  bl_models[[i]][["k"]][["s_KW"]] <- 30
  bl_models[[i]][["k"]][["s_index_by_AG"]] <- 30
}
# knots Bayern
bl_models$Bayern[["k"]][["s_index"]] <- 90
bl_models$Bayern[["k"]][["s_KW"]] <- 30
bl_models$Bayern[["k"]][["s_index_by_AG"]] <- 30

# knots Bawü
bl_models$`Baden-Wuerttemberg`[["k"]][["s_index"]] <- 90
bl_models$`Baden-Wuerttemberg`[["k"]][["s_KW"]] <- 30
bl_models$`Baden-Wuerttemberg`[["k"]][["s_index_by_AG"]] <- 30

# knots Berlin
bl_models$Berlin[["k"]][["s_index"]] <- 90
bl_models$Berlin[["k"]][["s_KW"]] <- 25
bl_models$Berlin[["k"]][["s_index_by_AG"]] <- 30

# knots Brandenburg (Qian)
bl_models$Brandenburg[["k"]][["s_index"]] <- 90
bl_models$Brandenburg[["k"]][["s_KW"]] <- 30
bl_models$Brandenburg[["k"]][["s_index_by_AG"]] <- 30

# knots Bremen
bl_models$Bremen
bl_models$Bremen
bl_models$Bremen

# knots Hamburg

# knots Hessen

# knots Mecklenburg-V

# knots Niedersachsen

# knots Nordrhein-W

# knots Rheinland-Pf

# knots Saarland

# knots Bremen

# knots Sachsen

# knots Sachsen-A

# knots Schleswig-Hol

# knots Thueringen




for (i in seq_along(list_of_dfs)) {
  bl_name <- names(list_of_dfs)[[i]]
  bl_models[[bl_name]][["model"]] <- gam(Hospitalisierung ~ Neuerkrankung * Altersgruppe +
                               s(index, bs = "ps", k = bl_models[[bl_name]][["k"]][["s_index"]]) + 
                               s(Kalenderwoche, bs = "cc", k = bl_models[[bl_name]][["k"]][["s_KW"]]) +
                               s(index, bs = "ps", by = Altersgruppe, k = bl_models[[bl_name]][["k"]][["s_index_by_AG"]]),
                             data = list_of_dfs[[i]],
                             method = "REML",
                             family = "nb",
                             knots = list(Kalenderwoche = c(0.5, 53.5)))
}

for (i in seq_along(bl_models)) {
  gam.check(bl_models[[i]][["model"]])
}


```