---
title: "baden-württemberg"
author: "Alexander Marquard / 11779957"
date: "13 1 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(mgcv)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")

## Erstelle List mit Datensatz zu jedem Bundesland
list_of_dfs <- split(final_df, as.factor(final_df$Bundesland))
# bawü <- dplyr::filter(final_df, Bundesland == "Baden-Württemberg")
```

```{r boxplots}
lapply(list_of_dfs, function(x) {
  plot(x$Altersgruppe, log(x$Hospitalisierung + 1), 
       main = unique(x$Bundesland),
       ylab = "log(Hospitalisiert)",
       xlab = "Altersgruppen")
})
```

```{r Baden-Württemberg}
## Ergänze indizes

list_of_dfs$`Baden-Wuerttemberg` <- list_of_dfs$`Baden-Wuerttemberg` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

bawue_gam <- gam(Hospitalisierung ~ Neuerkrankung * Altersgruppe +
                 s(index, bs = "ps", k = 90) + 
                 s(Kalenderwoche, bs = "cc", k = 30) +
                 s(index, bs = "ps", by = Altersgruppe, k = 30),
               data = list_of_dfs$`Baden-Wuerttemberg`,
               method = "REML",
               family = "nb",
               knots = list(Kalenderwoche = c(0.5, 53.5)))
summary(bawue_gam)
gam.check(bawue_gam)
plot(bawue_gam)
for (x in unique(list_of_dfs$`Baden-Wuerttemberg`$Altersgruppe)) {
  pdata <- list_of_dfs$`Baden-Wuerttemberg` %>% filter(Altersgruppe == x)
  pdata <- cbind(pdata, predict(bawue_gam, pdata, type = "response", se = T))
  pdata <- transform(pdata, upr = fit + 2 * se.fit, lwr = fit - 2 * se.fit)
  plot(x = pdata$Meldedatum, y = pdata$Hospitalisierung, type = "l", main = x)
  polygon(x = c(rev(pdata$Meldedatum),pdata$Meldedatum), y = c(rev(pdata$lwr), pdata$upr), col = alpha("grey80", 0.4), border = NA)
  lines(x = pdata$Meldedatum, y = pdata$fit, col = "blue", type = "l", lwd = 2)
}

```
```{r bawue ohne Altersgruppe}

list_of_dfs$`Baden-Wuerttemberg` <- select(list_of_dfs$`Baden-Wuerttemberg`, -Altersgruppe)
list_of_dfs$`Baden-Wuerttemberg` <- list_of_dfs$`Baden-Wuerttemberg` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))

# ergänze index
list_of_dfs$`Baden-Wuerttemberg`$index <- seq(1,nrow(list_of_dfs$`Baden-Wuerttemberg`))
  
bawue_gam2 <- gam(Hospitalisierung ~ Neuerkrankung +
                 s(index, k = 50, bs = "ps") + 
                 s(Kalenderwoche, bs = "cc", k = 20),
               data = list_of_dfs$`Baden-Wuerttemberg`,
               method = "REML",
               family = "nb",
               knots = list(Kalenderwoche = c(0.5, 53.5)))
               #,correlation = corARMA(form=~1|index, p = 1, q = 1))
summary(bawue_gam2)
gam.check(bawue_gam2)

plot(bawue_gam2)

bawue_gamm <- gamm(Hospitalisierung ~ Neuerkrankung +
                 s(index, k = 50, bs = "ps") + 
                 s(Kalenderwoche, bs = "cc", k = 20),
               data = list_of_dfs$`Baden-Wuerttemberg`,
               method = "REML",
               family = "nb",
               knots = list(Kalenderwoche = c(0.5, 53.5)))

## R stürzt ab
auto.arima(resid(bawue_gamm, type = "normalized"))
bawue_gamm2 <- gamm(Hospitalisierung ~ Neuerkrankung +
                 s(index, k = 50, bs = "ps") + 
                 s(Kalenderwoche, bs = "cc", k = 20),
               data = list_of_dfs$`Baden-Wuerttemberg`,
               method = "REML",
               family = "nb",
               knots = list(Kalenderwoche = c(0.5, 53.5)),
               correlation = corARMA(form=~1|index, p = 5))

```
