---
title: "bayern"
author: "Alexander Marquard / 11779957"
date: "13 1 2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(mgcv)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")

## Erstelle Liste mit Datensatz zu jedem Bundesland
list_of_dfs <- split(final_df, as.factor(final_df$Bundesland))
# bawü <- dplyr::filter(final_df, Bundesland == "Baden-Württemberg")
```

```{r boxplots}
lapply(list_of_dfs, function(x) {
  plot(x$Altersgruppe, log(x$Hospitalisierung + 1), 
       main = unique(x$Bundesland),
       ylab = "log(Hospitalisiert)",
       xlab = "Altersgruppen")
})


hist(list_of_dfs$Bayern$Hospitalisierung, breaks = 50)
list_of_dfs$Bayern %>%
  group_by(Altersgruppe) %>%
  summarise(m_hosp = mean(Hospitalisierung),
            v_hosp = var(Hospitalisierung))

```

```{r Bayern}
## Ergänze indizes

list_of_dfs$Bayern <- list_of_dfs$Bayern %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

list_of_dfs$Bayern$Altersgruppe <- as.factor(list_of_dfs$Bayern$Altersgruppe)

list_of_dfs$Bayern$Altersgruppe <- relevel(list_of_dfs$Bayern$Altersgruppe, ref = "00-04")

bay_gam <- gam(Hospitalisierung ~ Altersgruppe +
                 s(index, bs = "ps", k = 100, by = Altersgruppe),
               data = list_of_dfs$Bayern,
               method = "REML",
               family = poisson(),
               knots = list(Kalenderwoche = c(1, 53)))
summary(bay_gam)
gam.check(bay_gam)
plot(bay_gam)
vis.gam(bay_gam, type = "link", plot.type = "persp")

for (x in unique(list_of_dfs$Bayern$Altersgruppe)) {
  pdata <- list_of_dfs$Bayern %>% filter(Altersgruppe == x)
  pdata <- cbind(pdata, predict(bay_gam, pdata, type = "response", se = T))
  pdata <- transform(pdata, upr = fit + 2 * se.fit, lwr = fit - 2 * se.fit)
  plot(x = pdata$Meldedatum, y = pdata$Hospitalisierung, type = "l", main = x)
  polygon(x = c(rev(pdata$Meldedatum),pdata$Meldedatum), y = c(rev(pdata$lwr), pdata$upr), col = alpha("grey80", 0.4), border = NA)
  lines(x = pdata$Meldedatum, y = pdata$fit, col = "blue", type = "l", lwd = 2)
}
```

```{r güte des modells}
# wähle ein Jahr zum modellieren
diagnosis_df <- data.frame(mape = numeric(10), iteration = numeric(10))
forecast_res <- data.frame(Meldedatum = character(10), 
                           Hosp_one_week = numeric(10), 
                           Hosp_two_week = numeric(10))

for (i in seq(0,8)) {
  train_df <- list_of_dfs$Bayern[1: ((98 + i)*6),]
  test_df <- list_of_dfs$Bayern[((98 + i) * 6 + 1):((100 + i)*6),]
  bay_train <- bay_train <- gam(Hospitalisierung ~ Neuerkrankung * Altersgruppe + 
                 s(Kalenderwoche, bs = "cc", k = 53, by = Altersgruppe),
               data = train_df,
               method = "REML",
               family = poisson(link = "log"),
               knots = list(Kalenderwoche = c(0.5, 53.5)),
               weights = seq(0,10,length.out = nrow(train_df)))
  
  forecast_l <- cbind(test_df, predict(bay_train, newdata = test_df, type = "response", se.fit = T))
  diagnosis_df$rmse[i+1] <- MAPE(forecast_l$Hospitalisierung, forecast_l$fit)
  diagnosis_df$iteration[i+1] <- i+1
  forecast <- forecast_l %>% group_by(Bundesland, Meldedatum) %>%
    summarise(Hospitalisierung = sum(fit))
  forecast_res$Meldedatum[i + 1] <- as.character(forecast$Meldedatum[1])
  forecast_res$Meldedatum[i + 2] <- as.character(forecast$Meldedatum[2])
  forecast_res$Hosp_one_week[i + 1] <- forecast$Hospitalisierung[1]
  forecast_res$Hosp_two_week[i + 2] <- forecast$Hospitalisierung[2]
}

df <- list_of_dfs$Bayern %>%
  group_by(Bundesland, Meldedatum) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
forecast_res$Meldedatum <- as.Date(forecast_res$Meldedatum)

ggplot(left_join(df, forecast_res[-c(1,10),], by = "Meldedatum")) +
  geom_line(aes(x = Meldedatum, y = Hospitalisierung,col = "black")) +
  geom_line(aes(x = Meldedatum, y = Hosp_one_week,col = "orange") ) +
  geom_line(aes(x = Meldedatum, y = Hosp_two_week,col = "red")) +
  scale_colour_manual(name = 'legend', 
         values =c('black'='black','orange'='orange', "red" = "red"), labels = c('true','one week', "two weeks")) +
  theme_minimal()
  

```

```{r Auf Altersgruppen-ebene}
bayern_dfs <- split(list_of_dfs$Bayern, list_of_dfs$Bayern$Altersgruppe)

for (x in bayern_dfs) {
  plot(y = x$Hospitalisierung, x = x$Meldedatum, type = "l", main = unique(x$Altersgruppe))
}

# Bei 0-4 und 5-14 macht eine Betrachtung als 4-wöchige hosp mehr sinn
bayern_0_4 <- bayern_dfs$`00-04` %>%
  mutate(index_2 = ifelse(index %% 4 == 1, 1, 0),
         Neuerkrankung_monat = Neuerkrankung + 
           lag(Neuerkrankung, default = 0, n = 1) +
           lag(Neuerkrankung, default = 0, n = 2) +
           lag(Neuerkrankung, default = 0, n = 3),
         Hospitalisierung_monat = Hospitalisierung +
           lag(Hospitalisierung, default = 0, n = 1) +
           lag(Hospitalisierung, default = 0, n = 2) +
           lag(Hospitalisierung, default = 0, n = 2)) %>%
  filter(index_2 != 0)

bayern_0_4$index <- seq(1, nrow(bayern_0_4))
  
plot(bayern_0_4$Meldedatum, bayern_0_4$Hospitalisierung_monat, type = "l")

bayern_0_4$Jahreszeit <- as.factor(bayern_0_4$Jahreszeit)
bayern_0_4$Kalenderwoche <- as.numeric(bayern_0_4$Kalenderwoche)

model_bay_0_4 <- gam(Hospitalisierung_monat ~ Neuerkrankung_monat + Jahreszeit +
                       s(index, bs = "ps", k = 15),
                     family = "nb",
                     data = bayern_0_4,
                     method = "REML")
summary(model_bay_0_4)
gam.check(model_bay_0_4)
plot(x = c(bayern_0_4$Meldedatum,"2022-01-03"), y = c(bayern_0_4$Hospitalisierung_monat, 150), type = "l")
lines(x = bayern_0_4$Meldedatum, y = fitted.values(model_bay_0_4), type = "l", col = "blue")
lines(x = as.Date("2022-01-03", format = "%Y-%m-%d"), y = predict(model_bay_0_4, newdata = data.frame(Neuerkrankung_monat = bayern_0_4$Neuerkrankung_monat[nrow(bayern_0_4)],
                                            Jahreszeit = "Winter", index = 25), type = "response"), col = "orange", type = "p")

#Jahreszeiten
for (x in bayern_dfs) {
  plot(x = x$Jahreszeit, y = log(x$Hospitalisierung + 1), main = unique(x$Altersgruppe))
  axis(1, x$Meldedatum, format(x$Meldedatum, "%b %d"), cex.axis = 0.7)
}

# Altersgruppen
for (x in bayern_dfs) {
  plot(x$Meldedatum, x$Hospitalisierung, type = "l", xaxt = "n", main = unique(x$Altersgruppe))
  axis(1, x$Meldedatum, format(x$Meldedatum, "%b %d"), cex.axis = 0.7)
}

# Verschiedene Modelle

model_gam5 <- gam(Hospitalisierung ~ Neuerkrankung + Jahreszeit +
                    s(index, Jahreszeit, bs = "ps", k = 20),
                  family = "nb",
                  data = bayern_dfs$`35+`[-seq(95,96,1),], 
                  method = "REML")
summary(model_gam5)
plot(model_gam5)
gam.check(model_gam5, rep = 500)

# Overdispersion
sum(residuals(model_gam5, type = "pearson")^2)/df.residual(model_gam5)
# -> 1.2 
# should be 1. Really close!

plot(x = bayern_dfs$`35+`$Meldedatum, y = bayern_dfs$`35+`$Hospitalisierung, col = "blue", type = "l",ylim = c(0, 3500))
lines(x = bayern_dfs$`35+`$Meldedatum[-seq(95,96,1)],
     y = fitted.values(model_gam5),
     type = "l")
lines(x = bayern_dfs$`35+`$Meldedatum[seq(95,96,1)], 
      y = predict(object = model_gam5, newdata = bayern_dfs$`35+`[seq(95,96,1),], type = "response"),
      type = "p", col = "orange")
abline(v =bayern_dfs$`35+`$Meldedatum[seq(96,96,1)], lty = "dotted")
abline(v =bayern_dfs$`35+`$Meldedatum[seq(95,95,1)], lty = "dotted")

# annahme einer neg.binom verteilung ist für 35+ gut, für die restlichen
# altersgruppen jedoch nicht

for (x in bayern_dfs) {
  print(unique(x$Altersgruppe))
  model_x <- gam(Hospitalisierung ~ Neuerkrankung + Jahreszeit +
                    s(index, k = 50, bs = "ps"),
                    family = "nb",
                    data = bayern_dfs$`00-04`[-seq(95,96,1),], 
                    method = "REML")
  summary(model_x)
  plot(model_x)
  gam.check(model_x, rep = 500)
  
  # Overdispersion
  # sum(residuals(model_x, type = "pearson")^2)/df.residual(model_x)
  # -> 1.2 
  # should be 1. Really close!
  
  plot(x = x$Meldedatum, y = x$Hospitalisierung, col = "blue", type = "l",ylim = c(0, 3500))
  lines(x = x$Meldedatum[-seq(95,96,1)],
       y = fitted.values(model_x),
       type = "l")
  lines(x = x$Meldedatum[seq(95,96,1)], 
        y = predict(object = model_x, newdata = x[seq(95,96,1),], type = "response"),
        type = "p", col = "orange")
  abline(v = x$Meldedatum[seq(96,96,1)], lty = "dotted")
  abline(v = x$Meldedatum[seq(95,95,1)], lty = "dotted")
}

plot(y = bayern_dfs$`00-04`$Hospitalisierung, x = bayern_dfs$`00-04`$Meldedatum, type ="l")


```
