---
title: "ets"
author: "Alexander Marquard / 11779957"
date: "6 3 2022"
output: pdf_document
---

```{r prep}
final_df <- readRDS("../final_df.RDS")
impfungen <- readRDS("../../data_truth/RKI/impfungen.Rds")

N <- sum(unique(final_df$population))
```
## Exponentielles Glätten

```{r}
p_ets_neuer <- final_df %>%
  group_by(Meldedatum) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung))

ab <- ets(as.ts(p_ets_neuer$Neuerkrankung), model = "ZZZ")
auto.arima(as.ts(p_ets_neuer$Neuerkrankung))
autoplot(forecast(ab, h = 2))
```

```{r}

erg_l <- list()
for (j in unique(final_df$Bundesland)) {
  p_ets <- final_df %>%
    filter(Bundesland == j) %>%
    group_by(Meldedatum) %>%
    summarise(Hospitalisierung = sum(Hospitalisierung))

  erg_l[[as.character(j)]][["df"]] <- p_ets
  n <- nrow(p_ets)
  aa <- list()
  for (i in 0:10) {
    erg <- ets(as.ts(p_ets$Hospitalisierung[1: (n - 10 + i)]), model = "AAN")
    aa[["plots"]][[as.character(i)]] <- autoplot(forecast(erg, h = 2)) + theme_minimal()
    aa[["erg"]][[as.character(i)]] <- forecast(erg, h = 2)
  }
  erg_l[[as.character(j)]][["fit"]] <- aa
}

erg_l$Bayern$fit$erg$`0`

forecast_ls <- list()
bl_names <- names(erg_l)
for (j in 0:10) {
  forecast_res <- c()
  hosp_t <- c()
  for (i in names(erg_l)) {
    # one week forecast für jedes Bundesland
    owf <- erg_l[[i]]$fit$erg[[as.character(j)]]$mean[[1]]
    # index
    index <- as.numeric(rownames(as.data.frame(erg_l[[i]]$fit$erg[[as.character(j)]])[1,]))
    # Hosp
    forecast_res <- append(forecast_res, owf)
    if (j == 10) next
    date <- erg_l[[i]]$df$Meldedatum[[index]]
    hosp <- erg_l[[i]]$df$Hospitalisierung[[index]]
    hosp_t <- append(hosp_t, hosp)
  }
  names(forecast_res) <- bl_names
  forecast_ls[[as.character(j)]][["Date"]] <- date
  forecast_ls[[as.character(j)]][["fitted_per_bl"]] <- forecast_res
  forecast_ls[[as.character(j)]][["total_pred"]] <- sum(forecast_res)
  forecast_ls[[as.character(j)]][["true_val"]] <- sum(hosp_t)
}
forecast_ls$`7`

final_df %>% filter(Bundesland == "Bayern") %>% group_by(Meldedatum) %>%
              summarise(Hospitalisierung = sum(Hospitalisierung))




erg_l$Bayern$fit$plots$`10` +
  geom_line(data = final_df %>% filter(Bundesland == "Bayern") %>% group_by(Meldedatum) %>%
              summarise(Hospitalisierung = sum(Hospitalisierung)), aes(x=1:nrow(erg_l$Bayern$df), y = Hospitalisierung))

ggplot() +
  geom_ribbon(data = as.data.frame(aa$erg$`0`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`0`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`0`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`0`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`1`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`1`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`1`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`1`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`2`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`2`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`2`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`2`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`3`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`3`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`3`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`3`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`4`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`4`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`4`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`4`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`5`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`5`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`5`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`5`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`6`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`6`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`6`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`6`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`7`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`7`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`7`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`7`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`8`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`8`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`8`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`8`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`9`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`9`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`9`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`9`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`10`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`10`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`10`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`10`))),
                  y = `Point Forecast`), col = "blue") +
  geom_line(data = p_ets, aes(x=1:nrow(p_ets), y = Hospitalisierung)) +
  xlab("Zeit") +
  ylab("Hospitalisierung") +
  theme_minimal()

```

## Exponential Smoothing mit Hosp/Infekt

```{r}
erg_l <- list()
for (j in unique(final_df$Bundesland)) {
  p_hosp_inf <- final_df %>%
    filter(Bundesland == j) %>%
  group_by(Meldedatum) %>%
  summarise(Hospitalisierung = sum(Hospitalisierung),
            Neuerkrankung = sum(Neuerkrankung)) %>%
  mutate(hosprate = Hospitalisierung / (Neuerkrankung + 1))

  erg_l[[as.character(j)]][["df"]] <- p_hosp_inf
  n <- nrow(p_hosp_inf)
  aa <- list()
  for (i in 0:10) {
    erg <- ets(as.ts(p_hosp_inf$hosprate[-(n - 10 + i: n)]), model = "ZZN")
    aa[["plots"]][[as.character(i)]] <- autoplot(forecast(erg, h = 2)) + theme_minimal()
    aa[["erg"]][[as.character(i)]] <- forecast(erg, h = 2)
  }
  erg_l[[as.character(j)]][["fit"]] <- aa
}

forecast_ls <- list()
for (j in 1:10) {
  forecast_res <- c()
  hosp_t <- c()
  for (i in names(erg_l)) {
    # one week forecast für jedes Bundesland
    owf <- erg_l[[i]]$fit$erg[[j]]$mean[[1]]
    # index
    index <- as.numeric(rownames(as.data.frame(erg_l[[i]]$fit$erg[[j]])[1,]))
    # Neuerkrankung
    neuerk <- erg_l[[i]]$df$Neuerkrankung[[index]]
    # Hosp
    hosp <- erg_l[[i]]$df$Hospitalisierung[[index]]
    # pred Hosp
    pred_hosp <- owf * neuerk
    forecast_res <- append(forecast_res, pred_hosp)
    hosp_t <- append(hosp_t, hosp)
  }
  forecast_ls[[as.character(j)]][["fitted_per_bl"]] <- forecast_res
  forecast_ls[[as.character(j)]][["total_pred"]] <- sum(forecast_res)
  forecast_ls[[as.character(j)]][["true_val"]] <- sum(hosp_t)
}
forecast_ls$`9`

erg_l$Bayern$fit$plots$`9` +
  geom_line(data = erg_l$Bayern$df, aes(x=1:nrow(erg_l$Bayern$df), y = hosprate))



ggplot() +
  geom_ribbon(data = as.data.frame(aa$erg$`0`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`0`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`0`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`0`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`1`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`1`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`1`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`1`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`2`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`2`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`2`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`2`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`3`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`3`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`3`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`3`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`4`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`4`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`4`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`4`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`5`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`5`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`5`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`5`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`6`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`6`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`6`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`6`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`7`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`7`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`7`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`7`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`8`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`8`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`8`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`8`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`9`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`9`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`9`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`9`))),
                  y = `Point Forecast`), col = "blue") +
  geom_ribbon(data = as.data.frame(aa$erg$`10`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`10`))), 
                ymin = `Lo 95`, ymax = `Hi 95`), fill = "grey75") +
  geom_line(data = as.data.frame(aa$erg$`10`), 
            aes(x = as.numeric(rownames(as.data.frame(aa$erg$`10`))),
                  y = `Point Forecast`), col = "blue") +
  geom_line(data = p_hosp_inf, aes(x=1:nrow(p_hosp_inf), y = hosprate)) +
  xlab("Zeit") +
  ylab("Hospitalisierung") +
  theme_minimal()
```
