---
title: "Mecklenburg-Vorpommern"
author: "Qian Feng/12136134"
date: "1/29/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("dpl")
library(dplyr)
library(tibble)
library(stringr)
library(readr)
library(tidyr)
library(lubridate)
library(tidyverse)
library(mgcv)
```

```{r prep}
final_df <- readRDS("../final_df.RDS")

## Erstelle List mit Datensatz zu jedem Bundesland
list_of_dfs <- split(final_df, as.factor(final_df$Bundesland))
```

```{r boxplots}
lapply(list_of_dfs, function(x) {
  plot(x$Altersgruppe, log(x$Hospitalisierung + 1), 
       main = unique(x$Bundesland),
       ylab = "log(Hospitalisiert)",
       xlab = "Altersgruppen")
})
```

```{r Mecklenburg-Vorpommern}
# Ausgehend von den Altersboxplots können die Gruppen 00-04 und 05-14, 35-59 und 60-79 zusammengeführt werden
levels(list_of_dfs$`Mecklenburg-Vorpommern`$Altersgruppe) <- c("00-14", "00-14", "15-34", "35-79","35-79","80+")

list_of_dfs$`Mecklenburg-Vorpommern` <- list_of_dfs$`Mecklenburg-Vorpommern` %>%
  group_by(Meldedatum, Kalenderjahr, Kalenderwoche, Altersgruppe, Jahreszeit) %>%
  summarise(Neuerkrankung = sum(Neuerkrankung),
            Hospitalisierung = sum(Hospitalisierung))
## Ergänze indizes

list_of_dfs$`Mecklenburg-Vorpommern` <- list_of_dfs$`Mecklenburg-Vorpommern` %>%
  group_by(Altersgruppe) %>%
  mutate(index = row_number(Altersgruppe))

meckgvor_gam <- gam(Hospitalisierung ~
                 Altersgruppe +
                 s(index, bs = "ps", k = 90) + 
                 s(Neuerkrankung, bs = "ps", k = 30) +
                 s(Neuerkrankung, by = Altersgruppe, bs = "ps", k = 30) +
                 s(Kalenderwoche, bs = "cc", k = 25) +
                 s(index, by = Altersgruppe, bs = "ps", k = 30),
               data = list_of_dfs$`Mecklenburg-Vorpommern`,
               method = "REML",
               family = "nb",
               knots = list(Kalenderwoche = c(0.5, 53.5)))
summary(meckgvor_gam)
gam.check(meckgvor_gam)
plot(meckgvor_gam)
# obwohl gam.check zeigt, dass k ist niederig, kann man nicht k erhoehen weiter, denn wenn man k erhoeht, dann gibt es warning. Deviance explained = 97.8% und die Grafik unten ist gut.

# Hier ist es evtl besser eine andere Verteilung zu wählen:
hist(list_of_dfs$`Mecklenburg-Vorpommern`$Hospitalisierung, breaks = 30)
meckgvor_gam_cop <- gam(Hospitalisierung ~
                 Altersgruppe * Neuerkrankung +
                 s(index, bs = "ps", k = 90) + 
                 s(Kalenderwoche, bs = "cc", k = 25) +
                 s(index, by = Altersgruppe, bs = "ps", k = 30),
               data = list_of_dfs$`Mecklenburg-Vorpommern`,
               method = "REML",
               family = poisson(link = "log"),
               knots = list(Kalenderwoche = c(0.5, 53.5)))
summary(meckgvor_gam_cop)
gam.check(meckgvor_gam_cop)
plot(meckgvor_gam_cop)

for (x in unique(list_of_dfs$`Mecklenburg-Vorpommern`$Altersgruppe)) {
  pdata <- list_of_dfs$`Mecklenburg-Vorpommern` %>% filter(Altersgruppe == x)
  pdata <- cbind(pdata, predict(meckgvor_gam_cop, pdata, type = "response", se = T))
  pdata <- transform(pdata, upr = fit + 2 * se.fit, lwr = fit - 2 * se.fit)
  plot(x = pdata$Meldedatum, y = pdata$Hospitalisierung, type = "l", main = x)
  polygon(x = c(rev(pdata$Meldedatum),pdata$Meldedatum), y = c(rev(pdata$lwr), pdata$upr), col = alpha("grey80", 0.4), border = NA)
  lines(x = pdata$Meldedatum, y = pdata$fit, col = "blue", type = "l", lwd = 2)
}
```


